//! Domain-independent Čech cochain complex.
//!
//! Stalks are arbitrary-dimension `Vec<f32>`, restriction maps are
//! `DMatrix<f32>` projections, and edge taxonomy is a generic label.
//!
//! The complex computes:
//! - δ⁰: C⁰ → C¹ (coboundary operator — checks stalk consistency across edges)
//! - δ¹: C¹ → C² (cycle detection — checks face consistency)
//! - H⁰ = ker(δ⁰) (globally consistent stalks — valid cache entries)
//! - H¹ = ker(δ¹) / im(δ⁰) (independent cycles — fundamental invalidation paths)

use std::collections::{HashMap, HashSet};

use nalgebra::{DMatrix, DVector};
use nalgebra_sparse::{CooMatrix, CscMatrix};

use crate::sparse::SparseOps;

/// Numerical tolerance for zero comparisons.
const EPS: f32 = 1e-4;

/// Sparse matrix entry threshold — values below this are treated as zero.
const SPARSE_EPS: f32 = 1e-10;

/// Maximum dense matrix elements before falling back to skip exact SVD.
const MAX_DENSE_ELEMENTS: usize = 10_000_000;

// ---------------------------------------------------------------------------
// Core types
// ---------------------------------------------------------------------------

/// A stalk: the data assigned to a cell. Dimension is dynamic.
#[derive(Debug, Clone)]
pub struct Stalk {
    pub data: Vec<f32>,
}

impl Stalk {
    pub fn new(data: Vec<f32>) -> Self {
        Self { data }
    }

    pub fn dim(&self) -> usize {
        self.data.len()
    }
}

/// A restriction map: projects a node's stalk onto an edge's agreement space.
///
/// For an edge connecting nodes u and v with stalk dimension S and edge
/// agreement dimension D, the restriction map is a D×S matrix that extracts
/// the relevant coordinates.
#[derive(Debug, Clone)]
pub struct RestrictionMap {
    pub matrix: DMatrix<f32>,
}

impl RestrictionMap {
    /// Create a restriction map from a D×S matrix.
    pub fn new(matrix: DMatrix<f32>) -> Self {
        Self { matrix }
    }

    /// Create a 1D projection that extracts a single coordinate.
    pub fn project_dim(stalk_dim: usize, coord: usize) -> Self {
        let mut m = DMatrix::zeros(1, stalk_dim);
        m[(0, coord)] = 1.0;
        Self { matrix: m }
    }

    /// Create an identity restriction (all dimensions agree).
    pub fn identity(dim: usize) -> Self {
        Self {
            matrix: DMatrix::identity(dim, dim),
        }
    }

    /// Create a weighted projection: extracts `coords` with `weights`.
    pub fn weighted(stalk_dim: usize, coords_weights: &[(usize, f32)]) -> Self {
        let mut m = DMatrix::zeros(1, stalk_dim);
        for &(coord, weight) in coords_weights {
            m[(0, coord)] = weight;
        }
        Self { matrix: m }
    }
}

/// A 0-cell or 1-cell in the complex.
#[derive(Debug, Clone)]
pub struct Cell {
    pub id: u32,
    /// 0 = node, 1 = edge.
    pub dimension: u8,
    pub stalk: Stalk,
    /// Optional label for edge taxonomy (domain-specific, opaque to the algebra).
    pub label: Option<String>,
    /// Whether this cell was generated by presheaf composition (transitive closure).
    pub is_virtual: bool,
}

/// A 2-cell (face) bounding a cycle of edges.
#[derive(Debug, Clone)]
pub struct Cell2 {
    pub id: u32,
    /// Edge IDs and their orientations (+1.0 or -1.0) around the face.
    pub edges: Vec<(u32, f32)>,
    /// Stalk dimension of this face.
    pub dimension: usize,
}

/// A constraint violation detected by the coboundary operator.
#[derive(Debug, Clone)]
pub struct Violation {
    pub edge_id: u32,
    pub dimension_index: usize,
    /// Negative margin = violation. Magnitude indicates severity.
    pub margin: f32,
    pub is_virtual: bool,
}

/// Cohomology result from H⁰ computation.
#[derive(Debug)]
pub struct H0Result {
    /// Groups of node IDs that are mutually consistent.
    pub consistent_groups: Vec<Vec<u32>>,
    /// Total defect: ||δ⁰(stalks)||². Zero = entire complex is consistent.
    pub defect: f32,
}

// ---------------------------------------------------------------------------
// CellComplex
// ---------------------------------------------------------------------------

/// A domain-independent Čech cochain complex.
///
/// Manages 0-cells (nodes with stalks), 1-cells (edges with restriction maps),
/// and 2-cells (faces bounding cycles). Computes coboundary operators δ⁰ and δ¹,
/// detects violations, and calculates cohomology groups H⁰ and H¹.
pub struct CellComplex {
    pub nodes: Vec<u32>,
    pub edges: Vec<u32>,
    pub faces: Vec<u32>,
    pub cells: HashMap<u32, Cell>,
    pub face_cells: HashMap<u32, Cell2>,
    /// (node_id, edge_id) → restriction map.
    pub restriction_maps: HashMap<(u32, u32), RestrictionMap>,
    /// edge_id → (source_node_id, target_node_id).
    pub incidence: HashMap<u32, (u32, u32)>,
    /// Stalk dimension of 0-cells. All nodes must share the same dimension.
    node_stalk_dim: usize,
}

impl CellComplex {
    /// Create an empty complex with the given node stalk dimension.
    pub fn new(node_stalk_dim: usize) -> Self {
        Self {
            nodes: Vec::new(),
            edges: Vec::new(),
            faces: Vec::new(),
            cells: HashMap::new(),
            face_cells: HashMap::new(),
            restriction_maps: HashMap::new(),
            incidence: HashMap::new(),
            node_stalk_dim,
        }
    }

    /// Add a 0-cell (node) with the given stalk data.
    ///
    /// # Panics
    /// Panics if `data.len() != self.node_stalk_dim`.
    pub fn add_node(&mut self, id: u32, data: Vec<f32>) {
        assert_eq!(
            data.len(),
            self.node_stalk_dim,
            "Node stalk must be {}D, got {}D",
            self.node_stalk_dim,
            data.len()
        );
        self.cells.insert(
            id,
            Cell {
                id,
                dimension: 0,
                stalk: Stalk::new(data),
                label: None,
                is_virtual: false,
            },
        );
        self.nodes.push(id);
    }

    /// Add a 1-cell (edge) connecting source → target with the given
    /// agreement dimension, label, and restriction maps.
    #[allow(clippy::too_many_arguments)]
    pub fn add_edge(
        &mut self,
        edge_id: u32,
        source: u32,
        target: u32,
        agreement_dim: usize,
        label: Option<String>,
        map_source: RestrictionMap,
        map_target: RestrictionMap,
        is_virtual: bool,
    ) {
        self.cells.insert(
            edge_id,
            Cell {
                id: edge_id,
                dimension: 1,
                stalk: Stalk::new(vec![0.0; agreement_dim]),
                label,
                is_virtual,
            },
        );
        self.edges.push(edge_id);
        self.incidence.insert(edge_id, (source, target));
        self.restriction_maps.insert((source, edge_id), map_source);
        self.restriction_maps.insert((target, edge_id), map_target);
    }

    /// Add a 2-cell (face) bounding a cycle of edges.
    pub fn add_face(&mut self, face_id: u32, edges: &[(u32, f32)], dim: usize) {
        self.face_cells.insert(
            face_id,
            Cell2 {
                id: face_id,
                edges: edges.to_vec(),
                dimension: dim,
            },
        );
        self.faces.push(face_id);
    }

    // -----------------------------------------------------------------------
    // Presheaf composition (gluing axiom)
    // -----------------------------------------------------------------------

    /// Enforce transitive closure on edges with the given label.
    ///
    /// If A →(label) B →(label) C, adds a virtual edge A →(label) C with the
    /// same restriction maps. Ensures the presheaf composition axiom holds.
    pub fn enforce_transitive_closure(
        &mut self,
        label: &str,
        map_source: RestrictionMap,
        map_target: RestrictionMap,
        agreement_dim: usize,
    ) {
        // Collect directed pairs for the given label
        let mut pairs = Vec::new();
        for &edge_id in &self.edges {
            if let Some(cell) = self.cells.get(&edge_id)
                && cell.label.as_deref() == Some(label)
                && !cell.is_virtual
                && let Some(&(u, v)) = self.incidence.get(&edge_id)
            {
                pairs.push((u, v));
            }
        }

        let mut parent_to_children: HashMap<u32, Vec<u32>> = HashMap::new();
        for &(p, c) in &pairs {
            parent_to_children.entry(p).or_default().push(c);
        }

        let mut virtual_id = self.edges.iter().copied().max().unwrap_or(0) + 1;

        for &start in parent_to_children.keys() {
            let mut queue = vec![(start, 0u32)];
            let mut visited = HashSet::new();

            while let Some((curr, depth)) = queue.pop() {
                if visited.contains(&curr) {
                    continue;
                }
                visited.insert(curr);

                if depth > 1 {
                    self.add_edge(
                        virtual_id,
                        start,
                        curr,
                        agreement_dim,
                        Some(label.to_string()),
                        map_source.clone(),
                        map_target.clone(),
                        true,
                    );
                    virtual_id += 1;
                }

                if let Some(children) = parent_to_children.get(&curr) {
                    for &child in children {
                        queue.push((child, depth + 1));
                    }
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // Cycle detection → 2-cell generation
    // -----------------------------------------------------------------------

    /// Generate 2-cells (faces) from cycles in edges with the given label.
    ///
    /// Finds triangles via neighbor-set intersection and longer cycles (4-8)
    /// via bounded DFS. Returns the number of faces created.
    pub fn generate_faces_from_cycles(&mut self, label: &str, max_cycles: usize) -> usize {
        // Build (source, target) → edge_id map for the given label
        let mut edge_map: HashMap<(u32, u32), u32> = HashMap::new();
        let mut dep_edges = Vec::new();
        for &edge_id in &self.edges {
            if let Some(cell) = self.cells.get(&edge_id)
                && cell.label.as_deref() == Some(label)
                && let Some(&(src, tgt)) = self.incidence.get(&edge_id)
            {
                edge_map.insert((src, tgt), edge_id);
                dep_edges.push((src, tgt));
            }
        }

        if dep_edges.is_empty() {
            return 0;
        }

        let mut adjacency: HashMap<u32, Vec<u32>> = HashMap::new();
        let mut neighbor_set: HashMap<u32, HashSet<u32>> = HashMap::new();
        let mut all_nodes: HashSet<u32> = HashSet::new();

        for &(src, tgt) in &dep_edges {
            adjacency.entry(src).or_default().push(tgt);
            neighbor_set.entry(src).or_default().insert(tgt);
            all_nodes.insert(src);
            all_nodes.insert(tgt);
        }

        let max_existing_id = self.edges.iter().copied().max().unwrap_or(0);
        let mut face_id = max_existing_id + 200_000;
        let mut faces_created = 0usize;
        let mut seen_cycles: HashSet<Vec<u32>> = HashSet::new();

        let canonicalize = |cycle: &[u32]| -> Vec<u32> {
            if cycle.is_empty() {
                return vec![];
            }
            let min_pos = cycle
                .iter()
                .enumerate()
                .min_by_key(|&(_, &v)| v)
                .map(|(i, _)| i)
                .unwrap_or(0);
            (0..cycle.len())
                .map(|i| cycle[(min_pos + i) % cycle.len()])
                .collect()
        };

        // Phase 1: triangles via neighbor-set intersection
        for &(a, b) in &dep_edges {
            if faces_created >= max_cycles {
                break;
            }
            if let Some(b_neighbors) = adjacency.get(&b) {
                for &c in b_neighbors {
                    if faces_created >= max_cycles {
                        break;
                    }
                    if let Some(c_nset) = neighbor_set.get(&c)
                        && c_nset.contains(&a)
                    {
                        let canon = canonicalize(&[a, b, c]);
                        if seen_cycles.contains(&canon) {
                            continue;
                        }
                        seen_cycles.insert(canon);

                        let mut face_edges = Vec::new();
                        for &(s, t) in &[(a, b), (b, c), (c, a)] {
                            if let Some(&eid) = edge_map.get(&(s, t)) {
                                face_edges.push((eid, 1.0));
                            }
                        }
                        if face_edges.len() == 3 {
                            // All dependency edges are 1D
                            self.add_face(face_id, &face_edges, 1);
                            face_id += 1;
                            faces_created += 1;
                        }
                    }
                }
            }
        }

        // Phase 2: longer cycles (4-8) via bounded DFS
        let mut all_nodes_sorted: Vec<u32> = all_nodes.into_iter().collect();
        all_nodes_sorted.sort();

        for &start in &all_nodes_sorted {
            if faces_created >= max_cycles {
                break;
            }
            let mut stack: Vec<(u32, Vec<u32>)> = vec![(start, vec![start])];
            let mut visited: HashSet<u32> = HashSet::new();
            visited.insert(start);

            while let Some((node, path)) = stack.pop() {
                if faces_created >= max_cycles {
                    break;
                }
                if path.len() > 8 {
                    continue;
                }
                if let Some(neighbors) = adjacency.get(&node) {
                    for &next in neighbors {
                        if faces_created >= max_cycles {
                            break;
                        }
                        if next == start && path.len() >= 4 {
                            let canon = canonicalize(&path);
                            if seen_cycles.contains(&canon) {
                                continue;
                            }
                            seen_cycles.insert(canon);

                            let mut face_edges = Vec::new();
                            let mut all_found = true;
                            for i in 0..path.len() {
                                let src = path[i];
                                let tgt = path[(i + 1) % path.len()];
                                if let Some(&eid) = edge_map.get(&(src, tgt)) {
                                    face_edges.push((eid, 1.0));
                                } else {
                                    all_found = false;
                                    break;
                                }
                            }
                            if all_found && face_edges.len() >= 4 {
                                self.add_face(face_id, &face_edges, 1);
                                face_id += 1;
                                faces_created += 1;
                            }
                        } else if next != start && !visited.contains(&next) && path.len() < 8 {
                            visited.insert(next);
                            let mut new_path = path.clone();
                            new_path.push(next);
                            stack.push((next, new_path));
                        }
                    }
                }
            }
        }

        faces_created
    }

    // -----------------------------------------------------------------------
    // Coboundary operators
    // -----------------------------------------------------------------------

    /// Build the δ⁰: C⁰ → C¹ coboundary matrix (sparse CSC).
    ///
    /// For each edge e = (u, v) with restriction maps f_u, f_v:
    ///   (δ⁰ x)_e = f_v(x_v) - f_u(x_u)
    pub fn build_delta_0(&self) -> CscMatrix<f32> {
        let c0_dim = self.nodes.len() * self.node_stalk_dim;
        let mut c1_dim = 0;
        let mut edge_row_offsets = HashMap::new();
        for &edge_id in &self.edges {
            edge_row_offsets.insert(edge_id, c1_dim);
            c1_dim += self.cells.get(&edge_id).unwrap().stalk.dim();
        }

        let mut node_col_offsets = HashMap::new();
        for (i, &node_id) in self.nodes.iter().enumerate() {
            node_col_offsets.insert(node_id, i * self.node_stalk_dim);
        }

        let mut coo = CooMatrix::new(c1_dim, c0_dim);

        for &edge_id in &self.edges {
            let (u_id, v_id) = self.incidence.get(&edge_id).unwrap();
            let row_start = *edge_row_offsets.get(&edge_id).unwrap();
            let u_col_start = *node_col_offsets.get(u_id).unwrap();
            let v_col_start = *node_col_offsets.get(v_id).unwrap();

            let f_u = &self.restriction_maps.get(&(*u_id, edge_id)).unwrap().matrix;
            let f_v = &self.restriction_maps.get(&(*v_id, edge_id)).unwrap().matrix;

            // -f_u contribution
            for r in 0..f_u.nrows() {
                for c in 0..f_u.ncols() {
                    let val = -f_u[(r, c)];
                    if val.abs() > SPARSE_EPS {
                        coo.push(row_start + r, u_col_start + c, val);
                    }
                }
            }
            // +f_v contribution
            for r in 0..f_v.nrows() {
                for c in 0..f_v.ncols() {
                    let val = f_v[(r, c)];
                    if val.abs() > SPARSE_EPS {
                        coo.push(row_start + r, v_col_start + c, val);
                    }
                }
            }
        }

        CscMatrix::from(&coo)
    }

    /// Build the δ¹: C¹ → C² coboundary matrix (sparse CSC).
    pub fn build_delta_1(&self) -> CscMatrix<f32> {
        let mut c1_dim = 0;
        let mut edge_row_offsets = HashMap::new();
        for &edge_id in &self.edges {
            edge_row_offsets.insert(edge_id, c1_dim);
            c1_dim += self.cells.get(&edge_id).unwrap().stalk.dim();
        }

        let mut c2_dim = 0;
        let mut face_row_offsets = HashMap::new();
        for &face_id in &self.faces {
            face_row_offsets.insert(face_id, c2_dim);
            c2_dim += self.face_cells.get(&face_id).unwrap().dimension;
        }

        let mut coo = CooMatrix::new(c2_dim, c1_dim);

        for &face_id in &self.faces {
            let face = self.face_cells.get(&face_id).unwrap();
            let f_row = *face_row_offsets.get(&face_id).unwrap();

            for &(edge_id, sign) in &face.edges {
                let e_col = *edge_row_offsets.get(&edge_id).unwrap();
                let e_dim = self.cells.get(&edge_id).unwrap().stalk.dim();

                for i in 0..face.dimension.min(e_dim) {
                    if sign.abs() > SPARSE_EPS {
                        coo.push(f_row + i, e_col + i, sign);
                    }
                }
            }
        }

        CscMatrix::from(&coo)
    }

    /// Assert the cochain complex condition: δ¹ ∘ δ⁰ = 0.
    ///
    /// # Panics
    /// Panics if the condition is violated (max entry > 1e-4).
    pub fn assert_cochain_complex(&self) {
        if self.faces.is_empty() || self.edges.is_empty() {
            return;
        }
        let d0 = self.build_delta_0();
        let d1 = self.build_delta_1();

        let product_elements = d1.nrows() * d0.ncols();
        if product_elements > MAX_DENSE_ELEMENTS {
            return;
        }

        let dense_0 = SparseOps::to_dense(&d0);
        let dense_1 = SparseOps::to_dense(&d1);
        let product = &dense_1 * &dense_0;
        let max_entry = product.abs().max();
        assert!(
            max_entry < EPS,
            "δ¹∘δ⁰ ≠ 0 (max entry: {}). Cochain complex is invalid.",
            max_entry
        );
    }

    // -----------------------------------------------------------------------
    // Violation detection + cohomology
    // -----------------------------------------------------------------------

    /// Concatenate all node stalks into a single global section vector.
    pub fn global_section(&self) -> DVector<f32> {
        let mut x = Vec::with_capacity(self.nodes.len() * self.node_stalk_dim);
        for node_id in &self.nodes {
            x.extend_from_slice(&self.cells.get(node_id).unwrap().stalk.data);
        }
        DVector::from_vec(x)
    }

    /// Detect constraint violations via δ⁰. O(nnz).
    ///
    /// Returns edges where the coboundary margin is negative (constraint
    /// violated). Margin magnitude indicates severity.
    pub fn detect_violations(&self) -> Vec<Violation> {
        let delta = self.build_delta_0();
        let x = self.global_section();

        assert_eq!(
            delta.ncols(),
            x.len(),
            "Dimension mismatch: δ⁰ is {}×{}, section is {}",
            delta.nrows(),
            delta.ncols(),
            x.len()
        );

        let bounds = SparseOps::spmv(&delta, &x);
        let mut violations = Vec::new();
        let mut row_offset = 0;

        for &edge_id in &self.edges {
            let cell = self.cells.get(&edge_id).unwrap();
            let dim = cell.stalk.dim();

            for i in 0..dim {
                let val = bounds[row_offset + i];
                if val < -EPS {
                    violations.push(Violation {
                        edge_id,
                        dimension_index: i,
                        margin: val,
                        is_virtual: cell.is_virtual,
                    });
                }
            }
            row_offset += dim;
        }

        violations
    }

    /// Compute H⁰ — groups of nodes with consistent stalks.
    ///
    /// Uses the coboundary operator to compute per-edge defects, then
    /// union-find to group nodes connected by low-defect edges.
    pub fn compute_h0(&self, threshold: f32) -> H0Result {
        let delta = self.build_delta_0();
        let x = self.global_section();
        let image = SparseOps::spmv(&delta, &x);

        // Compute per-edge squared norms
        let mut edge_defects: HashMap<u32, f32> = HashMap::new();
        let mut row_offset = 0;
        for &edge_id in &self.edges {
            let dim = self.cells.get(&edge_id).unwrap().stalk.dim();
            let mut norm_sq = 0.0f32;
            for i in 0..dim {
                let v = image[row_offset + i];
                norm_sq += v * v;
            }
            edge_defects.insert(edge_id, norm_sq);
            row_offset += dim;
        }

        let total_defect: f32 = edge_defects.values().sum();

        // Union-find: merge nodes connected by low-defect edges
        let mut parent: HashMap<u32, u32> = HashMap::new();
        for &n in &self.nodes {
            parent.insert(n, n);
        }

        fn find(parent: &mut HashMap<u32, u32>, x: u32) -> u32 {
            let p = *parent.get(&x).unwrap_or(&x);
            if p == x {
                return x;
            }
            let root = find(parent, p);
            parent.insert(x, root);
            root
        }

        for &edge_id in &self.edges {
            if let Some(&defect) = edge_defects.get(&edge_id)
                && defect < threshold
                && let Some(&(u, v)) = self.incidence.get(&edge_id)
            {
                let ru = find(&mut parent, u);
                let rv = find(&mut parent, v);
                if ru != rv {
                    parent.insert(ru, rv);
                }
            }
        }

        // Collect groups
        let mut groups: HashMap<u32, Vec<u32>> = HashMap::new();
        for &n in &self.nodes {
            let root = find(&mut parent, n);
            groups.entry(root).or_default().push(n);
        }

        H0Result {
            consistent_groups: groups.into_values().collect(),
            defect: total_defect,
        }
    }

    /// Compute the H⁰ dimension (nullity of δ⁰ restricted to active constraints).
    pub fn h0_dimension(&self) -> usize {
        let delta = self.build_delta_0();
        let x = self.global_section();
        let bounds = SparseOps::spmv(&delta, &x);

        let active_rows: Vec<usize> = (0..bounds.len()).filter(|&i| bounds[i] <= EPS).collect();

        if active_rows.is_empty() {
            return self.nodes.len() * self.node_stalk_dim;
        }

        let ncols = delta.ncols();
        let active_elements = active_rows.len() * ncols;
        if active_elements > MAX_DENSE_ELEMENTS {
            return 0;
        }

        let mut row_map: HashMap<usize, usize> = HashMap::with_capacity(active_rows.len());
        for (new_r, &old_r) in active_rows.iter().enumerate() {
            row_map.insert(old_r, new_r);
        }

        let mut delta_active = DMatrix::zeros(active_rows.len(), ncols);
        for col_idx in 0..ncols {
            let col = delta.col(col_idx);
            for (&row_idx, &val) in col.row_indices().iter().zip(col.values().iter()) {
                if let Some(&new_r) = row_map.get(&row_idx) {
                    delta_active[(new_r, col_idx)] = val;
                }
            }
        }

        let svd = delta_active.svd(true, true);
        let rank = SparseOps::numerical_rank(&svd);
        ncols - rank
    }

    /// Compute the H¹ Betti number: dim(ker(δ¹) / im(δ⁰)).
    ///
    /// Measures independent cycles not bounded by faces. Uses randomized
    /// SVD (Halko-Martinsson-Tropp) for large matrices.
    pub fn h1_betti_number(&self) -> usize {
        if self.faces.is_empty() {
            return 0;
        }

        let delta_0 = self.build_delta_0();
        let delta_1 = self.build_delta_1();

        let max_rank_hint = self.faces.len() + self.edges.len();
        let rank_1 = SparseOps::rank_estimate(&delta_1, max_rank_hint);
        let nullity_1 = delta_1.ncols().saturating_sub(rank_1);
        let rank_0 = SparseOps::rank_estimate(&delta_0, max_rank_hint);

        nullity_1.saturating_sub(rank_0)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a simple 2-node complex with a 1D agreement edge.
    fn two_node_complex(a_val: f32, b_val: f32) -> CellComplex {
        let mut cx = CellComplex::new(2);
        cx.add_node(0, vec![a_val, 0.0]);
        cx.add_node(1, vec![b_val, 0.0]);
        // Edge checks that first coordinate agrees
        cx.add_edge(
            100,
            0,
            1,
            1,
            Some("test".into()),
            RestrictionMap::project_dim(2, 0),
            RestrictionMap::project_dim(2, 0),
            false,
        );
        cx
    }

    #[test]
    fn consistent_nodes_no_violations() {
        let cx = two_node_complex(5.0, 5.0);
        let violations = cx.detect_violations();
        assert!(violations.is_empty());
    }

    #[test]
    fn inconsistent_nodes_have_violations() {
        // a=5, b=3 → coboundary = f_v(b) - f_u(a) = 3 - 5 = -2 < 0
        let cx = two_node_complex(5.0, 3.0);
        let violations = cx.detect_violations();
        assert_eq!(violations.len(), 1);
        assert!(violations[0].margin < 0.0);
    }

    #[test]
    fn h0_groups_consistent_nodes() {
        let mut cx = CellComplex::new(2);
        cx.add_node(0, vec![1.0, 0.0]);
        cx.add_node(1, vec![1.0, 0.0]);
        cx.add_node(2, vec![9.0, 0.0]);
        // 0-1 agree, 1-2 disagree
        cx.add_edge(
            100,
            0,
            1,
            1,
            None,
            RestrictionMap::project_dim(2, 0),
            RestrictionMap::project_dim(2, 0),
            false,
        );
        cx.add_edge(
            101,
            1,
            2,
            1,
            None,
            RestrictionMap::project_dim(2, 0),
            RestrictionMap::project_dim(2, 0),
            false,
        );

        let h0 = cx.compute_h0(0.01);
        // Nodes 0 and 1 should be in the same group, node 2 separate
        assert!(h0.defect > 0.0);
        let has_pair = h0.consistent_groups.iter().any(|g| g.len() == 2);
        assert!(has_pair);
    }

    #[test]
    fn triangle_cycle_generates_face() {
        let mut cx = CellComplex::new(1);
        cx.add_node(0, vec![1.0]);
        cx.add_node(1, vec![2.0]);
        cx.add_node(2, vec![3.0]);

        let proj = RestrictionMap::identity(1);
        cx.add_edge(
            100,
            0,
            1,
            1,
            Some("dep".into()),
            proj.clone(),
            proj.clone(),
            false,
        );
        cx.add_edge(
            101,
            1,
            2,
            1,
            Some("dep".into()),
            proj.clone(),
            proj.clone(),
            false,
        );
        cx.add_edge(
            102,
            2,
            0,
            1,
            Some("dep".into()),
            proj.clone(),
            proj.clone(),
            false,
        );

        let n = cx.generate_faces_from_cycles("dep", 100);
        assert_eq!(n, 1);
        assert_eq!(cx.faces.len(), 1);
    }

    #[test]
    fn cochain_complex_condition_holds_for_triangle() {
        let mut cx = CellComplex::new(1);
        cx.add_node(0, vec![1.0]);
        cx.add_node(1, vec![2.0]);
        cx.add_node(2, vec![3.0]);

        let proj = RestrictionMap::identity(1);
        cx.add_edge(
            100,
            0,
            1,
            1,
            Some("dep".into()),
            proj.clone(),
            proj.clone(),
            false,
        );
        cx.add_edge(
            101,
            1,
            2,
            1,
            Some("dep".into()),
            proj.clone(),
            proj.clone(),
            false,
        );
        cx.add_edge(
            102,
            2,
            0,
            1,
            Some("dep".into()),
            proj.clone(),
            proj.clone(),
            false,
        );

        cx.generate_faces_from_cycles("dep", 100);
        cx.assert_cochain_complex(); // Should not panic
    }
}
