// Code generated by capnpc-go. DO NOT EDIT.

package cache

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type CacheLockfile capnp.Struct

// CacheLockfile_TypeID is the unique identifier for the type CacheLockfile.
const CacheLockfile_TypeID = 0xaeb5e58152e02fd8

func NewCacheLockfile(s *capnp.Segment) (CacheLockfile, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return CacheLockfile(st), err
}

func NewRootCacheLockfile(s *capnp.Segment) (CacheLockfile, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return CacheLockfile(st), err
}

func ReadRootCacheLockfile(msg *capnp.Message) (CacheLockfile, error) {
	root, err := msg.Root()
	return CacheLockfile(root.Struct()), err
}

func (s CacheLockfile) String() string {
	str, _ := text.Marshal(0xaeb5e58152e02fd8, capnp.Struct(s))
	return str
}

func (s CacheLockfile) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CacheLockfile) DecodeFromPtr(p capnp.Ptr) CacheLockfile {
	return CacheLockfile(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CacheLockfile) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CacheLockfile) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CacheLockfile) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CacheLockfile) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CacheLockfile) Meta() (Meta, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Meta(p.Struct()), err
}

func (s CacheLockfile) HasMeta() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CacheLockfile) SetMeta(v Meta) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewMeta sets the meta field to a newly
// allocated Meta struct, preferring placement in s's segment.
func (s CacheLockfile) NewMeta() (Meta, error) {
	ss, err := NewMeta(capnp.Struct(s).Segment())
	if err != nil {
		return Meta{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s CacheLockfile) Sources() (SourceEntry_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return SourceEntry_List(p.List()), err
}

func (s CacheLockfile) HasSources() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CacheLockfile) SetSources(v SourceEntry_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewSources sets the sources field to a newly
// allocated SourceEntry_List, preferring placement in s's segment.
func (s CacheLockfile) NewSources(n int32) (SourceEntry_List, error) {
	l, err := NewSourceEntry_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return SourceEntry_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s CacheLockfile) Topology() (TopologyEdge_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return TopologyEdge_List(p.List()), err
}

func (s CacheLockfile) HasTopology() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CacheLockfile) SetTopology(v TopologyEdge_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewTopology sets the topology field to a newly
// allocated TopologyEdge_List, preferring placement in s's segment.
func (s CacheLockfile) NewTopology(n int32) (TopologyEdge_List, error) {
	l, err := NewTopologyEdge_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return TopologyEdge_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s CacheLockfile) Root() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return common.Hash(p.Struct()), err
}

func (s CacheLockfile) HasRoot() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CacheLockfile) SetRoot(v common.Hash) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewRoot sets the root field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s CacheLockfile) NewRoot() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CacheLockfile_List is a list of CacheLockfile.
type CacheLockfile_List = capnp.StructList[CacheLockfile]

// NewCacheLockfile creates a new list of CacheLockfile.
func NewCacheLockfile_List(s *capnp.Segment, sz int32) (CacheLockfile_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[CacheLockfile](l), err
}

// CacheLockfile_Future is a wrapper for a CacheLockfile promised by a client call.
type CacheLockfile_Future struct{ *capnp.Future }

func (f CacheLockfile_Future) Struct() (CacheLockfile, error) {
	p, err := f.Future.Ptr()
	return CacheLockfile(p.Struct()), err
}
func (p CacheLockfile_Future) Meta() Meta_Future {
	return Meta_Future{Future: p.Future.Field(0, nil)}
}
func (p CacheLockfile_Future) Root() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(3, nil)}
}

type Meta capnp.Struct

// Meta_TypeID is the unique identifier for the type Meta.
const Meta_TypeID = 0x9192dcb4e7dc4f9a

func NewMeta(s *capnp.Segment) (Meta, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Meta(st), err
}

func NewRootMeta(s *capnp.Segment) (Meta, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Meta(st), err
}

func ReadRootMeta(msg *capnp.Message) (Meta, error) {
	root, err := msg.Root()
	return Meta(root.Struct()), err
}

func (s Meta) String() string {
	str, _ := text.Marshal(0x9192dcb4e7dc4f9a, capnp.Struct(s))
	return str
}

func (s Meta) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Meta) DecodeFromPtr(p capnp.Ptr) Meta {
	return Meta(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Meta) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Meta) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Meta) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Meta) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Meta) Producer() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Meta) HasProducer() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Meta) ProducerBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Meta) SetProducer(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Meta) ProducerVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Meta) HasProducerVersion() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Meta) ProducerVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Meta) SetProducerVersion(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Meta) SchemaVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Meta) HasSchemaVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Meta) SchemaVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Meta) SetSchemaVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Meta) InputProcessors() (ProcessorVersion_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return ProcessorVersion_List(p.List()), err
}

func (s Meta) HasInputProcessors() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Meta) SetInputProcessors(v ProcessorVersion_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewInputProcessors sets the inputProcessors field to a newly
// allocated ProcessorVersion_List, preferring placement in s's segment.
func (s Meta) NewInputProcessors(n int32) (ProcessorVersion_List, error) {
	l, err := NewProcessorVersion_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ProcessorVersion_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s Meta) GeneratedAtMs() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Meta) SetGeneratedAtMs(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// Meta_List is a list of Meta.
type Meta_List = capnp.StructList[Meta]

// NewMeta creates a new list of Meta.
func NewMeta_List(s *capnp.Segment, sz int32) (Meta_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[Meta](l), err
}

// Meta_Future is a wrapper for a Meta promised by a client call.
type Meta_Future struct{ *capnp.Future }

func (f Meta_Future) Struct() (Meta, error) {
	p, err := f.Future.Ptr()
	return Meta(p.Struct()), err
}

type ProcessorVersion capnp.Struct

// ProcessorVersion_TypeID is the unique identifier for the type ProcessorVersion.
const ProcessorVersion_TypeID = 0xffad8b1e38e36033

func NewProcessorVersion(s *capnp.Segment) (ProcessorVersion, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ProcessorVersion(st), err
}

func NewRootProcessorVersion(s *capnp.Segment) (ProcessorVersion, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ProcessorVersion(st), err
}

func ReadRootProcessorVersion(msg *capnp.Message) (ProcessorVersion, error) {
	root, err := msg.Root()
	return ProcessorVersion(root.Struct()), err
}

func (s ProcessorVersion) String() string {
	str, _ := text.Marshal(0xffad8b1e38e36033, capnp.Struct(s))
	return str
}

func (s ProcessorVersion) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProcessorVersion) DecodeFromPtr(p capnp.Ptr) ProcessorVersion {
	return ProcessorVersion(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProcessorVersion) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProcessorVersion) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProcessorVersion) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProcessorVersion) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProcessorVersion) Kind() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProcessorVersion) HasKind() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProcessorVersion) KindBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProcessorVersion) SetKind(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProcessorVersion) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ProcessorVersion) HasVersion() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProcessorVersion) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ProcessorVersion) SetVersion(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ProcessorVersion_List is a list of ProcessorVersion.
type ProcessorVersion_List = capnp.StructList[ProcessorVersion]

// NewProcessorVersion creates a new list of ProcessorVersion.
func NewProcessorVersion_List(s *capnp.Segment, sz int32) (ProcessorVersion_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ProcessorVersion](l), err
}

// ProcessorVersion_Future is a wrapper for a ProcessorVersion promised by a client call.
type ProcessorVersion_Future struct{ *capnp.Future }

func (f ProcessorVersion_Future) Struct() (ProcessorVersion, error) {
	p, err := f.Future.Ptr()
	return ProcessorVersion(p.Struct()), err
}

type SourceEntry capnp.Struct

// SourceEntry_TypeID is the unique identifier for the type SourceEntry.
const SourceEntry_TypeID = 0xa0af24f5c493ba54

func NewSourceEntry(s *capnp.Segment) (SourceEntry, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return SourceEntry(st), err
}

func NewRootSourceEntry(s *capnp.Segment) (SourceEntry, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return SourceEntry(st), err
}

func ReadRootSourceEntry(msg *capnp.Message) (SourceEntry, error) {
	root, err := msg.Root()
	return SourceEntry(root.Struct()), err
}

func (s SourceEntry) String() string {
	str, _ := text.Marshal(0xa0af24f5c493ba54, capnp.Struct(s))
	return str
}

func (s SourceEntry) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SourceEntry) DecodeFromPtr(p capnp.Ptr) SourceEntry {
	return SourceEntry(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SourceEntry) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SourceEntry) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SourceEntry) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SourceEntry) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SourceEntry) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SourceEntry) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SourceEntry) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SourceEntry) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s SourceEntry) InputHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return common.Hash(p.Struct()), err
}

func (s SourceEntry) HasInputHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SourceEntry) SetInputHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewInputHash sets the inputHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s SourceEntry) NewInputHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s SourceEntry) ChunkHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return common.Hash(p.Struct()), err
}

func (s SourceEntry) HasChunkHash() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s SourceEntry) SetChunkHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewChunkHash sets the chunkHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s SourceEntry) NewChunkHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s SourceEntry) Kind() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s SourceEntry) HasKind() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s SourceEntry) KindBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s SourceEntry) SetKind(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// SourceEntry_List is a list of SourceEntry.
type SourceEntry_List = capnp.StructList[SourceEntry]

// NewSourceEntry creates a new list of SourceEntry.
func NewSourceEntry_List(s *capnp.Segment, sz int32) (SourceEntry_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[SourceEntry](l), err
}

// SourceEntry_Future is a wrapper for a SourceEntry promised by a client call.
type SourceEntry_Future struct{ *capnp.Future }

func (f SourceEntry_Future) Struct() (SourceEntry, error) {
	p, err := f.Future.Ptr()
	return SourceEntry(p.Struct()), err
}
func (p SourceEntry_Future) InputHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(1, nil)}
}
func (p SourceEntry_Future) ChunkHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(2, nil)}
}

type TopologyEdge capnp.Struct

// TopologyEdge_TypeID is the unique identifier for the type TopologyEdge.
const TopologyEdge_TypeID = 0x9a72950624518364

func NewTopologyEdge(s *capnp.Segment) (TopologyEdge, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TopologyEdge(st), err
}

func NewRootTopologyEdge(s *capnp.Segment) (TopologyEdge, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TopologyEdge(st), err
}

func ReadRootTopologyEdge(msg *capnp.Message) (TopologyEdge, error) {
	root, err := msg.Root()
	return TopologyEdge(root.Struct()), err
}

func (s TopologyEdge) String() string {
	str, _ := text.Marshal(0x9a72950624518364, capnp.Struct(s))
	return str
}

func (s TopologyEdge) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TopologyEdge) DecodeFromPtr(p capnp.Ptr) TopologyEdge {
	return TopologyEdge(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TopologyEdge) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TopologyEdge) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TopologyEdge) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TopologyEdge) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TopologyEdge) From() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TopologyEdge) HasFrom() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TopologyEdge) FromBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TopologyEdge) SetFrom(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TopologyEdge) ToSource() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TopologyEdge) HasToSource() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TopologyEdge) ToSourceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TopologyEdge) SetToSource(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// TopologyEdge_List is a list of TopologyEdge.
type TopologyEdge_List = capnp.StructList[TopologyEdge]

// NewTopologyEdge creates a new list of TopologyEdge.
func NewTopologyEdge_List(s *capnp.Segment, sz int32) (TopologyEdge_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[TopologyEdge](l), err
}

// TopologyEdge_Future is a wrapper for a TopologyEdge promised by a client call.
type TopologyEdge_Future struct{ *capnp.Future }

func (f TopologyEdge_Future) Struct() (TopologyEdge, error) {
	p, err := f.Future.Ptr()
	return TopologyEdge(p.Struct()), err
}

const schema_ca7eca7eca7eca7e = "x\xda\x8c\x93\xcfk\x13[\x14\xc7\xcf\xf7\xdeI\xfb\xfa" +
	"H_2$\xeb\xd7M\x17\xaf\xa5O+uQ\\\xa9" +
	"\xa5 b0\xb7\xd6B\xc1E\x87\xc9m\x13\xda\xe4\x8e" +
	"w&\xb6\x85j\xf1\x17\x88?\xd0j\x0b\xd2\x95\x7f\x80" +
	"\xb5.\x14\xc4\xa5\xb8*\x88(\x08.\xba\x10D\x0a\xe2" +
	"\xd6\xf5\xc8\x9d)\x93\x89D(\xb3\xb9s\xcew\xe6\x9c" +
	"\xef\xe7\x9c;\xbc\x8d\xe3\xd6\x91\xde\xf7\x9c\x98\x18\xcat" +
	"\x85\x9bgw\xf7^\xec>\\#\x91\x05\xc2+;\xf1" +
	"C\x19\xab\x9b\xa8\xf0\x0e\xb7\x0b\x9f\xd0M4\xf2\x01}" +
	" \x84\x95\xeb\xa2\xbfkCo\x92\x9dM\x8b\x99\x11g" +
	"\xf8N\xc1\xe6\xe6\xd4\xcb\x17\x09\xe1\xe4\xebGo\x7f\xf6" +
	"o?\xf9M\x1b\xfd\xb8\xce\xdf\x14\x9a\x91\xf6\"\xdf#" +
	"\x84\x9f\x0f\x7f\x99\xb8\xfa\xed\xe5\xb3N\xda\x92\xf5\xb10" +
	"\x1d\x9d\xce[F;2\xf3u\xf4\xdf;[a\xa7\x1e" +
	"J\x99\xef\x85\xe9L\xa4\xcd,\xd2X\xe8:nU\x1e" +
	"r\x1dx\x0d\xefXI\x06\x0eQ\x19\x10En\x11Y" +
	" \xb2/\x9f&\x12+\x1c\xe2\x16\x83\x0d\x14a\x827" +
	"\xaf\x11\x89\x1b\x1c\xe2\x01\x83\xcdX\x11\x8c\xc8\xbe\xa7\x89" +
	"\xc4]\x0e\xf1\x98\xc1\xe6\xbc\x08Ndo\x18\xe5:\x87" +
	"x\xce\x00\xab\x08\x8b\xc8\xde2\xc2\xa7\x1c\xe2\x15C\xe8" +
	"iUi\xbaR\x13\x11\xb2\xc4\x90\xa5V\x0cSR\xfb" +
	"5\xd5he|\xb7*\xeb\xce\x94\xa4\xbe(\x91\xc4k" +
	"\x0d\xaf\x19\x94\xb5\x82+}_i\x9f\xf0\x0f\xa1\xcc\x81" +
	"|\x8b\x06\xc1\x04\xc39\xd9\x90\xda\x09$\xf5UN\x04" +
	"%\x1f=\xc4\xd0CHH0CbRyjA\xcd" +
	"-\x8fW\xe6dL\xe4\xaf\x84\xc8\xc0 \x91\xe8\xe7\x10" +
	"\xc3)\"\xff\x1bLC\x1cb\x94!7\xabU=i" +
	"-P\xe7TS\xbb2m\xb0\xadV\x9c\x1eo\x04z" +
	"9\xaa\x94O*9\xa6\xd2\x05\x0eQMU\x92\x13D" +
	"\xa2\xc2!\xbc\x14\xfb\xba\x09.p\x88\xa5\x14\xfb\xa6\xf9" +
	"\xdc\xe3\x10+\x0c9\xcf\x09\xaa\xed\xb8N9>\xa1\x8a" +
	"|\xb83\xf0\xf7\xfd\xea\xba\xf5\xc3\x10\xca\x9b\xee\xaa\xcd" +
	"\xc6\xfc\x9f\xb2\xb9\xf9Z\xa3\xd2\xd9\xc8\x98y9\xa3\xdc" +
	"\xf9\xd9\xda\x02\xe4A\xac\x9c$\x123q\x83\x89\x95e" +
	"Cr\x89C\xac\xa7\xac\xac\x0d\xb6v+W\x97\x81\x83" +
	"|\xebb\xc6\x8d\xad\xfa\x11G\xbf5\xf9\xe4~\xedO" +
	">\xd8\x1f\xaa\x99D\"J.l,\xcai\xa5\x82N" +
	"L\xd2F\xcbZ\xc5{6%u\xce\xec\xe1A\x16\xc4" +
	"x\xfd\x8fC\x1ce\xed\x0cW/\xc9\xb6]\xfe\x15\x00" +
	"\x00\xff\xff`\x9c\x13r"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ca7eca7eca7eca7e,
		Nodes: []uint64{
			0x9192dcb4e7dc4f9a,
			0x9a72950624518364,
			0xa0af24f5c493ba54,
			0xaeb5e58152e02fd8,
			0xffad8b1e38e36033,
		},
		Compressed: true,
	})
}
