// Code generated by capnpc-go. DO NOT EDIT.

package head

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type Head capnp.Struct

// Head_TypeID is the unique identifier for the type Head.
const Head_TypeID = 0xbc8eed64e8f5bae7

func NewHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 6})
	return Head(st), err
}

func NewRootHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 6})
	return Head(st), err
}

func ReadRootHead(msg *capnp.Message) (Head, error) {
	root, err := msg.Root()
	return Head(root.Struct()), err
}

func (s Head) String() string {
	str, _ := text.Marshal(0xbc8eed64e8f5bae7, capnp.Struct(s))
	return str
}

func (s Head) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Head) DecodeFromPtr(p capnp.Ptr) Head {
	return Head(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Head) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Head) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Head) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Head) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Head) RootHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Hash(p.Struct()), err
}

func (s Head) HasRootHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Head) SetRootHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewRootHash sets the rootHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewRootHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) ParentHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return common.Hash(p.Struct()), err
}

func (s Head) HasParentHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Head) SetParentHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewParentHash sets the parentHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewParentHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) Generation() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Head) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Head) SegmentBytes() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Head) SetSegmentBytes(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Head) UnboundFacts() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Head) SetUnboundFacts(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Head) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Head) HasSignature() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Head) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Head) SignerKid() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Head) HasSignerKid() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Head) SetSignerKid(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Head) TreeRoot() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return common.Hash(p.Struct()), err
}

func (s Head) HasTreeRoot() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Head) SetTreeRoot(v common.Hash) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewTreeRoot sets the treeRoot field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewTreeRoot() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) ParserId() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return common.Hash(p.Struct()), err
}

func (s Head) HasParserId() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Head) SetParserId(v common.Hash) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewParserId sets the parserId field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewParserId() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Head_List is a list of Head.
type Head_List = capnp.StructList[Head]

// NewHead creates a new list of Head.
func NewHead_List(s *capnp.Segment, sz int32) (Head_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 6}, sz)
	return capnp.StructList[Head](l), err
}

// Head_Future is a wrapper for a Head promised by a client call.
type Head_Future struct{ *capnp.Future }

func (f Head_Future) Struct() (Head, error) {
	p, err := f.Future.Ptr()
	return Head(p.Struct()), err
}
func (p Head_Future) RootHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(0, nil)}
}
func (p Head_Future) ParentHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(1, nil)}
}
func (p Head_Future) TreeRoot() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(4, nil)}
}
func (p Head_Future) ParserId() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(5, nil)}
}

const schema_c7c7ada1403b9f78 = "x\xdat\xcf\xb1j\x14A\x00\xc6\xf1\xef\x9b\x99\xdd\xbb" +
	"\xa8Kv\xd9\x11,\x12P\x88\xa0\xa0\xa2\xd8\x886A" +
	"A\xce\xd8\xb8\xb7\x9d\xdd\x98\x1dnOp\xf6\xd8\x9d\x03" +
	"m}\x00m\xec\xc5\x07\xf0\x05\xc4>\xe0\x8b\xc4\"\xe9" +
	"\x0cX(#s\xc8\xd9\x9c\xed\xefk\xfe_~\xbc\xaf" +
	"\xeed\x9d\x80\xa8v\x924\x1c\x7f9\xfb\xde\x9c\xbe\xfb" +
	"\x8a\xea<ex\xfd\xf1\xc1\xfe\xa7\xcfGGH\xd2\x11" +
	"P\xee\xf2my\x85#\xe0\xee.\x03\xf1(\xb4\xd64" +
	"\xb7\x0e\xcd\x82nq\x7fbM\x83gd\xb5'\x15\xa0" +
	"\x08\x14\xa7\x07@u\"Y\xfd\x14,H\xcd\x88g\xcf" +
	"\x81\xea\x87\xe4\x94\x82\x14\x9a\x02(~G\xfb%Y\x8f" +
	")XHjJ\xa0L\xf8\x12\xa8\x15%\xeb<\xba\x12" +
	"\x9a\x0a(\xb3\x95_\x88~)z\"4\x13\xa0\xbc\xc8" +
	")P\xeb\xe8\x97\xa3\xa7R3]eG\xdf\x89~-" +
	"\xfaH\xe9x\xa2\xbc\xca\x03\xa0\xde\x8b~;\xfa8\xd1" +
	"\x1c\x03\xe5\xcd\x95\xdf\x88~\x8f\x82\xa1\xef:?1C" +
	"\x0b\x80y\xf8v\xfd\xdc\xfb\xf6\x83:\x01\xc8\x1c\x0c\x0b" +
	"\xd3[\xe7'\x06rh7\xcc3\xeblo\xfc\x1c\xb2" +
	"s\xdc\x82\xe0\x16\x18\x06;{e\x9d\x7f\x88\xed7\xde" +
	"\x0ek^\xba\x17\xdd\xd25\x8f\xb1m\x0e\xfd?\x1e\xe6" +
	"3g\xfc\xb2\x07-3\x08f\x7f\xcd\xf6O\xe7`\xb3" +
	"6\xdf[;\xed:\xff\xdf\xce\xc1\xf6O\x9a\x8d\xeb\x9f" +
	"\x00\x00\x00\xff\xffM\x0el\xa6"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c7c7ada1403b9f78,
		Nodes: []uint64{
			0xbc8eed64e8f5bae7,
		},
		Compressed: true,
	})
}
