// Code generated by capnpc-go. DO NOT EDIT.

package head

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type Head capnp.Struct

// Head_TypeID is the unique identifier for the type Head.
const Head_TypeID = 0xbc8eed64e8f5bae7

func NewHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Head(st), err
}

func NewRootHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Head(st), err
}

func ReadRootHead(msg *capnp.Message) (Head, error) {
	root, err := msg.Root()
	return Head(root.Struct()), err
}

func (s Head) String() string {
	str, _ := text.Marshal(0xbc8eed64e8f5bae7, capnp.Struct(s))
	return str
}

func (s Head) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Head) DecodeFromPtr(p capnp.Ptr) Head {
	return Head(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Head) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Head) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Head) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Head) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Head) RootHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Hash(p.Struct()), err
}

func (s Head) HasRootHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Head) SetRootHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewRootHash sets the rootHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewRootHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) ParentHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return common.Hash(p.Struct()), err
}

func (s Head) HasParentHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Head) SetParentHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewParentHash sets the parentHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewParentHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) Generation() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Head) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Head) SegmentBytes() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Head) SetSegmentBytes(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// Head_List is a list of Head.
type Head_List = capnp.StructList[Head]

// NewHead creates a new list of Head.
func NewHead_List(s *capnp.Segment, sz int32) (Head_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[Head](l), err
}

// Head_Future is a wrapper for a Head promised by a client call.
type Head_Future struct{ *capnp.Future }

func (f Head_Future) Struct() (Head, error) {
	p, err := f.Future.Ptr()
	return Head(p.Struct()), err
}
func (p Head_Future) RootHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(0, nil)}
}
func (p Head_Future) ParentHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(1, nil)}
}

const schema_c7c7ada1403b9f78 = "x\xdal\xc91/\x04A\x18\xc6\xf1\xe7yg\x8f\x1c" +
	"\x11\xbb\xb9-)\x94\x1a\x89\x96\xe6B\xb3Qy[\x95" +
	"\x89\x9d\xdc\x9e0\xbbv\xa7\xb8KT\xa2\xa6\x91(\xc5" +
	"\x07\xf0\x05D\x7f\x89/r\x0aJ\xf5\xc8Et\xba\x7f" +
	"~\xff\xf4q\x98\xec\xae\xd5\x02\xd1\x8d\xdeR\x9c\xbf~" +
	"\x7f\x94_wo\xd0UJ\x9c<\xed\x0f\x9f_f3" +
	"\xf4d\x19\x18l\xf2f\xb0\xc5\xdf\x9a\xe30V\xce\x96" +
	";g\xb6\xa1o\xf6\x0agK\x1c\x93\x9a\x9a\x04H\x08" +
	"d\xf6\x08\xd0SC\xbd\x10fd\xce\x05\x8eO\x00\xad" +
	"\x0c5\x08)9\x05\xc8\xae\x16\xd6\x18\xea\xb503\xcc" +
	"i\x80lz\x0e\xe8\xc4Po\x85\xb1\xad\xebP\xd8\xae" +
	"\x02\xc04\xbeo\xaf\xdcW\x0f\xc9'@\xa6`ll" +
	"\xeb|(,LW\xfd\xb3G\xce\xbb\xd6\x861L\xed" +
	"\xd9\x87\xb0\x0f\xc6\xce\x8d.\x9d\x0f\x07X\x9f\x06\xd7\xfd" +
	"\xf1O\x00\x00\x00\xff\xff\xb7\x8f@\x83"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c7c7ada1403b9f78,
		Nodes: []uint64{
			0xbc8eed64e8f5bae7,
		},
		Compressed: true,
	})
}
