// Code generated by capnpc-go. DO NOT EDIT.

package head

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type Head capnp.Struct

// Head_TypeID is the unique identifier for the type Head.
const Head_TypeID = 0xbc8eed64e8f5bae7

func NewHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return Head(st), err
}

func NewRootHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return Head(st), err
}

func ReadRootHead(msg *capnp.Message) (Head, error) {
	root, err := msg.Root()
	return Head(root.Struct()), err
}

func (s Head) String() string {
	str, _ := text.Marshal(0xbc8eed64e8f5bae7, capnp.Struct(s))
	return str
}

func (s Head) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Head) DecodeFromPtr(p capnp.Ptr) Head {
	return Head(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Head) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Head) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Head) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Head) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Head) RootHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Hash(p.Struct()), err
}

func (s Head) HasRootHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Head) SetRootHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewRootHash sets the rootHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewRootHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) ParentHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return common.Hash(p.Struct()), err
}

func (s Head) HasParentHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Head) SetParentHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewParentHash sets the parentHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s Head) NewParentHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) Generation() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Head) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Head) SegmentBytes() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Head) SetSegmentBytes(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Head) UnboundFacts() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Head) SetUnboundFacts(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// Head_List is a list of Head.
type Head_List = capnp.StructList[Head]

// NewHead creates a new list of Head.
func NewHead_List(s *capnp.Segment, sz int32) (Head_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2}, sz)
	return capnp.StructList[Head](l), err
}

// Head_Future is a wrapper for a Head promised by a client call.
type Head_Future struct{ *capnp.Future }

func (f Head_Future) Struct() (Head, error) {
	p, err := f.Future.Ptr()
	return Head(p.Struct()), err
}
func (p Head_Future) RootHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(0, nil)}
}
func (p Head_Future) ParentHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(1, nil)}
}

const schema_c7c7ada1403b9f78 = "x\xdal\xc9\xbdJ\x03A\x18\x05\xd0{\xbf\xd9\x18\xa2" +
	"H2dK\x83X\xda\x08b\xa7MP\x90`\xe5\xb4" +
	"vcv\xc8*8\x1b\xb2\x1bP\xd0F\x14,\xfc+" +
	"\"X(j\xa5\x8d/ \xf6\x01_D\x0b-\xadG" +
	"\xd2\xa4\xb2=\xa7\xf6\xdc\x8c\x16\xa73\x81\x98\x99\xd2D" +
	"\xf8|\xfb\xfdJ~.\xdfa\xa6\xa8\xc2\xfe\xc3J\xf3" +
	"\xe9u8DI\xca@\xbd\xc1\xe3\xfa\x1c\xcb\xc0R\x83" +
	"\xb3\xc4ZH\x9dM\x16\xda\xb6K\xdf]n9\x9b`" +
	"\x934\xb1\x8a\x80\x88\x80>\xda\x00\xcc\xa1\xa29\x13j" +
	"2\xe6\x08O\xb7\x00s\xa2h\xae\x85\x94\x98\x02\xe8\x8b" +
	"\x91\x9d+\x9a[\xa1V\x8c\xa9\x00}\xb3\x0b\x98\x81\xa2" +
	"y\x14\xeaHbF\x80\xbe\x1f\xe1\x9d\xa2y\x11\x86^" +
	"\x96\x15-\x9b\xa7\x00X\x0b\x1f\xf3\x93W\xe9 \xfa\x06" +
	"\xc8\x1a\x18\xba\xb6\xe7|\xd1\xb2Py\xfaOw\x9cw" +
	"=[\xec@e\x9e\x15\x08+`\xc8]g\xcf\xf9b" +
	"\x15\xd5\x83\xc2\xe5c\xee\xfb\xed\xac\xef\x93uTm\xbb" +
	"\x18\xf3_\x00\x00\x00\xff\xff\xec\x06J\x87"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c7c7ada1403b9f78,
		Nodes: []uint64{
			0xbc8eed64e8f5bae7,
		},
		Compressed: true,
	})
}
