// Code generated by capnpc-go. DO NOT EDIT.

package net

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type Manifest capnp.Struct

// Manifest_TypeID is the unique identifier for the type Manifest.
const Manifest_TypeID = 0xbf587d79c5c85fea

func NewManifest(s *capnp.Segment) (Manifest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Manifest(st), err
}

func NewRootManifest(s *capnp.Segment) (Manifest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Manifest(st), err
}

func ReadRootManifest(msg *capnp.Message) (Manifest, error) {
	root, err := msg.Root()
	return Manifest(root.Struct()), err
}

func (s Manifest) String() string {
	str, _ := text.Marshal(0xbf587d79c5c85fea, capnp.Struct(s))
	return str
}

func (s Manifest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Manifest) DecodeFromPtr(p capnp.Ptr) Manifest {
	return Manifest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Manifest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Manifest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Manifest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Manifest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Manifest) Sequence() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Manifest) SetSequence(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Manifest) PublicKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Manifest) HasPublicKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Manifest) SetPublicKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Manifest) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Manifest) HasSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Manifest) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Manifest) ContentHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Manifest) HasContentHash() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Manifest) SetContentHash(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

// Manifest_List is a list of Manifest.
type Manifest_List = capnp.StructList[Manifest]

// NewManifest creates a new list of Manifest.
func NewManifest_List(s *capnp.Segment, sz int32) (Manifest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Manifest](l), err
}

// Manifest_Future is a wrapper for a Manifest promised by a client call.
type Manifest_Future struct{ *capnp.Future }

func (f Manifest_Future) Struct() (Manifest, error) {
	p, err := f.Future.Ptr()
	return Manifest(p.Struct()), err
}

type ToolCall capnp.Struct

// ToolCall_TypeID is the unique identifier for the type ToolCall.
const ToolCall_TypeID = 0xd1cff727fc66eef7

func NewToolCall(s *capnp.Segment) (ToolCall, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ToolCall(st), err
}

func NewRootToolCall(s *capnp.Segment) (ToolCall, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ToolCall(st), err
}

func ReadRootToolCall(msg *capnp.Message) (ToolCall, error) {
	root, err := msg.Root()
	return ToolCall(root.Struct()), err
}

func (s ToolCall) String() string {
	str, _ := text.Marshal(0xd1cff727fc66eef7, capnp.Struct(s))
	return str
}

func (s ToolCall) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ToolCall) DecodeFromPtr(p capnp.Ptr) ToolCall {
	return ToolCall(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ToolCall) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ToolCall) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ToolCall) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ToolCall) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ToolCall) UpstreamId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ToolCall) HasUpstreamId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ToolCall) UpstreamIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ToolCall) SetUpstreamId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ToolCall) ToolName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ToolCall) HasToolName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ToolCall) ToolNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ToolCall) SetToolName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ToolCall) ArgumentsJson() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s ToolCall) HasArgumentsJson() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ToolCall) SetArgumentsJson(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

// ToolCall_List is a list of ToolCall.
type ToolCall_List = capnp.StructList[ToolCall]

// NewToolCall creates a new list of ToolCall.
func NewToolCall_List(s *capnp.Segment, sz int32) (ToolCall_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[ToolCall](l), err
}

// ToolCall_Future is a wrapper for a ToolCall promised by a client call.
type ToolCall_Future struct{ *capnp.Future }

func (f ToolCall_Future) Struct() (ToolCall, error) {
	p, err := f.Future.Ptr()
	return ToolCall(p.Struct()), err
}

type ToolResult capnp.Struct

// ToolResult_TypeID is the unique identifier for the type ToolResult.
const ToolResult_TypeID = 0xb10fdc54de199edf

func NewToolResult(s *capnp.Segment) (ToolResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ToolResult(st), err
}

func NewRootToolResult(s *capnp.Segment) (ToolResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ToolResult(st), err
}

func ReadRootToolResult(msg *capnp.Message) (ToolResult, error) {
	root, err := msg.Root()
	return ToolResult(root.Struct()), err
}

func (s ToolResult) String() string {
	str, _ := text.Marshal(0xb10fdc54de199edf, capnp.Struct(s))
	return str
}

func (s ToolResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ToolResult) DecodeFromPtr(p capnp.Ptr) ToolResult {
	return ToolResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ToolResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ToolResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ToolResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ToolResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ToolResult) Content() (Content_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Content_List(p.List()), err
}

func (s ToolResult) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ToolResult) SetContent(v Content_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewContent sets the content field to a newly
// allocated Content_List, preferring placement in s's segment.
func (s ToolResult) NewContent(n int32) (Content_List, error) {
	l, err := NewContent_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Content_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ToolResult) IsError() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ToolResult) SetIsError(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// ToolResult_List is a list of ToolResult.
type ToolResult_List = capnp.StructList[ToolResult]

// NewToolResult creates a new list of ToolResult.
func NewToolResult_List(s *capnp.Segment, sz int32) (ToolResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[ToolResult](l), err
}

// ToolResult_Future is a wrapper for a ToolResult promised by a client call.
type ToolResult_Future struct{ *capnp.Future }

func (f ToolResult_Future) Struct() (ToolResult, error) {
	p, err := f.Future.Ptr()
	return ToolResult(p.Struct()), err
}

type Content capnp.Struct
type Content_body Content
type Content_body_Which uint16

const (
	Content_body_Which_text     Content_body_Which = 0
	Content_body_Which_binary   Content_body_Which = 1
	Content_body_Which_resource Content_body_Which = 2
)

func (w Content_body_Which) String() string {
	const s = "textbinaryresource"
	switch w {
	case Content_body_Which_text:
		return s[0:4]
	case Content_body_Which_binary:
		return s[4:10]
	case Content_body_Which_resource:
		return s[10:18]

	}
	return "Content_body_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Content_TypeID is the unique identifier for the type Content.
const Content_TypeID = 0x99f4e9aeaa7dcc84

func NewContent(s *capnp.Segment) (Content, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Content(st), err
}

func NewRootContent(s *capnp.Segment) (Content, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Content(st), err
}

func ReadRootContent(msg *capnp.Message) (Content, error) {
	root, err := msg.Root()
	return Content(root.Struct()), err
}

func (s Content) String() string {
	str, _ := text.Marshal(0x99f4e9aeaa7dcc84, capnp.Struct(s))
	return str
}

func (s Content) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Content) DecodeFromPtr(p capnp.Ptr) Content {
	return Content(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Content) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Content) Body() Content_body { return Content_body(s) }

func (s Content_body) Which() Content_body_Which {
	return Content_body_Which(capnp.Struct(s).Uint16(0))
}
func (s Content_body) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Content_body) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Content_body) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Content_body) Text() (string, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != text")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Content_body) HasText() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Content_body) TextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Content_body) SetText(v string) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetText(0, v)
}

func (s Content_body) Binary() (BinaryContent, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != binary")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return BinaryContent(p.Struct()), err
}

func (s Content_body) HasBinary() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Content_body) SetBinary(v BinaryContent) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBinary sets the binary field to a newly
// allocated BinaryContent struct, preferring placement in s's segment.
func (s Content_body) NewBinary() (BinaryContent, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewBinaryContent(capnp.Struct(s).Segment())
	if err != nil {
		return BinaryContent{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Content_body) Resource() ([]byte, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != resource")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Content_body) HasResource() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Content_body) SetResource(v []byte) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetData(0, v)
}

// Content_List is a list of Content.
type Content_List = capnp.StructList[Content]

// NewContent creates a new list of Content.
func NewContent_List(s *capnp.Segment, sz int32) (Content_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Content](l), err
}

// Content_Future is a wrapper for a Content promised by a client call.
type Content_Future struct{ *capnp.Future }

func (f Content_Future) Struct() (Content, error) {
	p, err := f.Future.Ptr()
	return Content(p.Struct()), err
}
func (p Content_Future) Body() Content_body_Future { return Content_body_Future{p.Future} }

// Content_body_Future is a wrapper for a Content_body promised by a client call.
type Content_body_Future struct{ *capnp.Future }

func (f Content_body_Future) Struct() (Content_body, error) {
	p, err := f.Future.Ptr()
	return Content_body(p.Struct()), err
}
func (p Content_body_Future) Binary() BinaryContent_Future {
	return BinaryContent_Future{Future: p.Future.Field(0, nil)}
}

type BinaryContent capnp.Struct

// BinaryContent_TypeID is the unique identifier for the type BinaryContent.
const BinaryContent_TypeID = 0xa5ce533a7069aaa9

func NewBinaryContent(s *capnp.Segment) (BinaryContent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return BinaryContent(st), err
}

func NewRootBinaryContent(s *capnp.Segment) (BinaryContent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return BinaryContent(st), err
}

func ReadRootBinaryContent(msg *capnp.Message) (BinaryContent, error) {
	root, err := msg.Root()
	return BinaryContent(root.Struct()), err
}

func (s BinaryContent) String() string {
	str, _ := text.Marshal(0xa5ce533a7069aaa9, capnp.Struct(s))
	return str
}

func (s BinaryContent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BinaryContent) DecodeFromPtr(p capnp.Ptr) BinaryContent {
	return BinaryContent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BinaryContent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BinaryContent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BinaryContent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BinaryContent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BinaryContent) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s BinaryContent) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BinaryContent) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s BinaryContent) MimeType() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BinaryContent) HasMimeType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BinaryContent) MimeTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BinaryContent) SetMimeType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// BinaryContent_List is a list of BinaryContent.
type BinaryContent_List = capnp.StructList[BinaryContent]

// NewBinaryContent creates a new list of BinaryContent.
func NewBinaryContent_List(s *capnp.Segment, sz int32) (BinaryContent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[BinaryContent](l), err
}

// BinaryContent_Future is a wrapper for a BinaryContent promised by a client call.
type BinaryContent_Future struct{ *capnp.Future }

func (f BinaryContent_Future) Struct() (BinaryContent, error) {
	p, err := f.Future.Ptr()
	return BinaryContent(p.Struct()), err
}

const schema_a25bb2a310446125 = "x\xdalSOH\x14m\x1c\xfe=\xef;~~\xca" +
	"\xee\xb7;\xdf\xf8\x1d\xbeS\x04E%)v\x93\x85P" +
	"\xfc\x03i\x1a\xbe\xb6\x82\xd4!g\xd7W\x1d\x98\x9d\x19" +
	"gf\xd1\x85D\x02;u\xeb\x96\x87\xa0\xc2\x83B\x89" +
	"\x1d\xbb\x04A\xd0!\x0a\xefQ\xd0%\xec\xd0)\xf0R" +
	"\xbd\xf1\xce\xea\xecj\xde\x86\x87\xe7\xf7>\xcf\xf3{~" +
	"\xd3\xb3\x8c~\xe3Rv\x89\x13\x13\xe7[\xfeRko" +
	"W\xb6\x9e\xed}\x7f@\xa2\x1dPg\xed\xa1\xfc\x93\xe7" +
	"7\x1fS\x0bZ\x89\xacG\xb8om&_\x1b\xe8#" +
	"\xa8\xcd-'(\\\x7f\xb7Af{3\x97i\xc6&" +
	"^Y;\x09\xf7)\x96\x08\xea\xd3\xc3\xff?\x16?\xe4" +
	"vN|8\xcb\xb6\xac\xff\x921\x93i\xf2\xd7[o" +
	"^\xd7V\xa6_\x1e'sMYa\xeb\xd6\xdd\x84|" +
	"\x87}!\xa8\xcf\xa7K{\xf7:\xdd]\x12\xff\x02\x8d" +
	"\x00Sh\x05'\xb2$\x7fA\xb0$\xdf&\xa8\xfdo" +
	"s?\xce\xed\xbf\xdf=f8y\x16\xc6\xba\xd5f\xe8" +
	"\xaf\x16c\x9b\xba\x94'\xe3\xee\xb2\x1dx\x08\x0a\x83\xbe" +
	"\x17K\x0f\xf1\x04 \x0cn\x10\xa1I\xd5\xccv\x12\xcb" +
	"\x95\xfc\xd9Z:\xc2\x82\xc2\x80\xe3\xd9a\xad>\x18\x93" +
	"\x1e\xfc[\x0f\x1a 2/t\x12\x893\x1c\xa2\x87\xc1" +
	"\x04:\xa0\xc1\xaeQ\"q\x91C\xf42\xe4f\xed\xd8" +
	"F\x96\x18\xb2\x04Uq*\xb2X\x0b$\x11!C\x0c" +
	"\x19B\xb3\xb9\xa2\xef\xbb\x932\x17U\xdd\xf8\x98\xcc\xc0" +
	"\x81L?\xc3\xa1\xcae\x8d\xf5r\x88!\x86\xd5r\xdd" +
	"\x1d\xfe!Lp \xdf\xd8\x1dA\x83\xabN4\x1c\x86" +
	"~\x08\x10\x03\x8e\xaa\x8e\xdb\x9e3'y\x94h\xe6S" +
	"M[\xa7\x98\xe1\x10nC\xd3\x99$\x12\x0b\x1c\"f" +
	"0\x19:\xc0\x88\xccE\x0d\x06\x1c\xe26\x83\xc9Y\x87" +
	"\xae\xca\xac\x95\x88\xc42\x87XcP\x91\\\xacJ\xaf" +
	"\x9c\xc4n#\x866\x82\x0a\xaa%\xd7)_\x95\x84Z" +
	"\xba\x9e\xc8\x99\xf7\xec\xb8\x1a\x12d\x8a\x1d$\xbbB\xad" +
	"v\xb4\x90\xa2\x7f4\xda\x17w\xeb\xdeD\x86\x1b\x19\xa5" +
	"\x92\x00\xc3\xba\x9b~\x0e1\xc6\x90\xc5/U\x8f0R" +
	" \x12C\x1cb\x82!\xcb~\xaaz\x86q\x1dv\x8c" +
	"CL3\xe4b\xb9\x1c\x1f\xd6\xd3WJ\xdaG\xbe\xf1" +
	"\x87\x10\x90'\xa8PF~5\xac\x87:\xc1\x96\xeer" +
	"\xd0\xe6\xae\xab\xb7\x9aI\xb7:|\xa3!\x9f\x1eL\xb3" +
	"\xba\xc9X\xdd\xd2TH$\x8a\x1cb\x86AU\x83(" +
	"\x0e\xa5]!>2\x9b^N\xec\xfb\xee5\xbbr\xe4" +
	"\x9a\xecp\xbeZ\xd1wz*\x1a\x8d|\xef\xd0\xd9\xef" +
	"\x00\x00\x00\xff\xffW\x81\xfb\xac"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a25bb2a310446125,
		Nodes: []uint64{
			0x99f4e9aeaa7dcc84,
			0xa5ce533a7069aaa9,
			0xb10fdc54de199edf,
			0xbf587d79c5c85fea,
			0xd16c2a8be96221e2,
			0xd1cff727fc66eef7,
		},
		Compressed: true,
	})
}
