// Code generated by capnpc-go. DO NOT EDIT.

package common

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Position capnp.Struct

// Position_TypeID is the unique identifier for the type Position.
const Position_TypeID = 0xb15cd2b768ffe71c

func NewPosition(s *capnp.Segment) (Position, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Position(st), err
}

func NewRootPosition(s *capnp.Segment) (Position, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Position(st), err
}

func ReadRootPosition(msg *capnp.Message) (Position, error) {
	root, err := msg.Root()
	return Position(root.Struct()), err
}

func (s Position) String() string {
	str, _ := text.Marshal(0xb15cd2b768ffe71c, capnp.Struct(s))
	return str
}

func (s Position) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Position) DecodeFromPtr(p capnp.Ptr) Position {
	return Position(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Position) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Position) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Position) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Position) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Position) Line() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Position) SetLine(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Position) Column() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s Position) SetColumn(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s Position) Byte() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Position) SetByte(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// Position_List is a list of Position.
type Position_List = capnp.StructList[Position]

// NewPosition creates a new list of Position.
func NewPosition_List(s *capnp.Segment, sz int32) (Position_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Position](l), err
}

// Position_Future is a wrapper for a Position promised by a client call.
type Position_Future struct{ *capnp.Future }

func (f Position_Future) Struct() (Position, error) {
	p, err := f.Future.Ptr()
	return Position(p.Struct()), err
}

type Range capnp.Struct

// Range_TypeID is the unique identifier for the type Range.
const Range_TypeID = 0xb70d94b5bbba004a

func NewRange(s *capnp.Segment) (Range, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Range(st), err
}

func NewRootRange(s *capnp.Segment) (Range, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Range(st), err
}

func ReadRootRange(msg *capnp.Message) (Range, error) {
	root, err := msg.Root()
	return Range(root.Struct()), err
}

func (s Range) String() string {
	str, _ := text.Marshal(0xb70d94b5bbba004a, capnp.Struct(s))
	return str
}

func (s Range) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Range) DecodeFromPtr(p capnp.Ptr) Range {
	return Range(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Range) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Range) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Range) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Range) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Range) Start() (Position, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Position(p.Struct()), err
}

func (s Range) HasStart() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Range) SetStart(v Position) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStart sets the start field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s Range) NewStart() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Range) End() (Position, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Position(p.Struct()), err
}

func (s Range) HasEnd() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Range) SetEnd(v Position) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEnd sets the end field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s Range) NewEnd() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Range_List is a list of Range.
type Range_List = capnp.StructList[Range]

// NewRange creates a new list of Range.
func NewRange_List(s *capnp.Segment, sz int32) (Range_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Range](l), err
}

// Range_Future is a wrapper for a Range promised by a client call.
type Range_Future struct{ *capnp.Future }

func (f Range_Future) Struct() (Range, error) {
	p, err := f.Future.Ptr()
	return Range(p.Struct()), err
}
func (p Range_Future) Start() Position_Future {
	return Position_Future{Future: p.Future.Field(0, nil)}
}
func (p Range_Future) End() Position_Future {
	return Position_Future{Future: p.Future.Field(1, nil)}
}

type Hash capnp.Struct

// Hash_TypeID is the unique identifier for the type Hash.
const Hash_TypeID = 0xec0494688f0a29ca

func NewHash(s *capnp.Segment) (Hash, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hash(st), err
}

func NewRootHash(s *capnp.Segment) (Hash, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hash(st), err
}

func ReadRootHash(msg *capnp.Message) (Hash, error) {
	root, err := msg.Root()
	return Hash(root.Struct()), err
}

func (s Hash) String() string {
	str, _ := text.Marshal(0xec0494688f0a29ca, capnp.Struct(s))
	return str
}

func (s Hash) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Hash) DecodeFromPtr(p capnp.Ptr) Hash {
	return Hash(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Hash) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Hash) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Hash) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Hash) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Hash) Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Hash) HasBytes() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Hash) SetBytes(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Hash_List is a list of Hash.
type Hash_List = capnp.StructList[Hash]

// NewHash creates a new list of Hash.
func NewHash_List(s *capnp.Segment, sz int32) (Hash_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Hash](l), err
}

// Hash_Future is a wrapper for a Hash promised by a client call.
type Hash_Future struct{ *capnp.Future }

func (f Hash_Future) Struct() (Hash, error) {
	p, err := f.Future.Ptr()
	return Hash(p.Struct()), err
}

type NodeRef capnp.Struct

// NodeRef_TypeID is the unique identifier for the type NodeRef.
const NodeRef_TypeID = 0xd0d235685d85719f

func NewNodeRef(s *capnp.Segment) (NodeRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NodeRef(st), err
}

func NewRootNodeRef(s *capnp.Segment) (NodeRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NodeRef(st), err
}

func ReadRootNodeRef(msg *capnp.Message) (NodeRef, error) {
	root, err := msg.Root()
	return NodeRef(root.Struct()), err
}

func (s NodeRef) String() string {
	str, _ := text.Marshal(0xd0d235685d85719f, capnp.Struct(s))
	return str
}

func (s NodeRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NodeRef) DecodeFromPtr(p capnp.Ptr) NodeRef {
	return NodeRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NodeRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NodeRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NodeRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NodeRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NodeRef) SourceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s NodeRef) HasSourceId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NodeRef) SourceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s NodeRef) SetSourceId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s NodeRef) NodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s NodeRef) HasNodeId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s NodeRef) NodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s NodeRef) SetNodeId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s NodeRef) Range() (Range, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Range(p.Struct()), err
}

func (s NodeRef) HasRange() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s NodeRef) SetRange(v Range) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewRange sets the range field to a newly
// allocated Range struct, preferring placement in s's segment.
func (s NodeRef) NewRange() (Range, error) {
	ss, err := NewRange(capnp.Struct(s).Segment())
	if err != nil {
		return Range{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// NodeRef_List is a list of NodeRef.
type NodeRef_List = capnp.StructList[NodeRef]

// NewNodeRef creates a new list of NodeRef.
func NewNodeRef_List(s *capnp.Segment, sz int32) (NodeRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[NodeRef](l), err
}

// NodeRef_Future is a wrapper for a NodeRef promised by a client call.
type NodeRef_Future struct{ *capnp.Future }

func (f NodeRef_Future) Struct() (NodeRef, error) {
	p, err := f.Future.Ptr()
	return NodeRef(p.Struct()), err
}
func (p NodeRef_Future) Range() Range_Future {
	return Range_Future{Future: p.Future.Field(2, nil)}
}

const schema_b0c0debaadc0deb0 = "x\xdal\x91Ak\x13A\x14\xc7\xff\xff7[\x9bJ" +
	"\x96d\xd9\x1c\x85\x88x\xb0BEE/\xb9\xa4\x07\x0b" +
	"\xdd\xd2H\xa6x\xf0\xa0\x875;6\x81f\xa6fS" +
	"\xc4\x0f\xe0Y\x90\x9e\xbcx\x17\xa4U\x90B\xbd\xf4&" +
	"x\x92~\x80\xde\x8a\x14\xec\x17\x10de\"ij\xf4" +
	"\xb6\xef\xedo\xe6\xfd\xfeo\xaa?\x17\x83[\xe1\x17\x81" +
	"\xe8\xcb3\x17\x8aK\xdf\x8b\xee\xde\xe1\xa3\x0f\xd0!\xa5" +
	"\xd8=:x\xbf\x7ft\xb0\x8b`\x16\x88\x13~\x8c5" +
	"\xfdW\x8b;\xe0\xaf\x95\xfd\xcf\x9f\xb6\xc3\xbd(\xe4\x04" +
	"\x9c\x11\xff\xff\x98o\xe2\xd3\x11y\xc2\xe7`\xf1\xf6\xd9" +
	"\xcb\xc7\xdd\xbb\x87\xdf\xf07\xab<\xb1$\xef\xe2\xd6\xe8" +
	"T\";`\xf1u\xfe\xe2\xab\xeev\xf0c\x8a\x1d\xdd" +
	"v,\xaf\xe3\xd3\x11{\"M,\x14\x1d\xd7\xef;{" +
	"\xa3\xc3t\xd3n6\xda.\xaf\xf7\x86=g\xdb\xa4." +
	"\xab\x00\x08\x08DK\xd7\x01\xbd\xa8\xa8W\x85\x11Y\xa3" +
	"o&\x0d@\xdfS\xd4ma$\xacQ\x80\xa8\xe5\xc9" +
	"eE\xfd@X\xd9\xe8Y\xc3\x12\x84%\xb0\xd9q\x1b" +
	"[};.+O^\x0c\x0d\xe7 \x9c\x03\xa7$\xd6" +
	"R\xab\xd6\x8d7(\x9d\x19\xcc\xdf\x06\xf4UE}\xf3" +
	"\x9c\xc1\xc2\x15@_S\xd4w\x84\xf5|\x98\x0e\x86\xac" +
	"N\xd6\x0f\xb2\x0a\xce\x1a\x9b\xfd\xdb\x9d\x9ax\xdfe\x15" +
	"\xb3f\x9eN\xa5^9\x17p<\xb3\xd5\x98\x04\x8cD" +
	"\xfe\xa4\xd6\xdenUQ?\x14\x16\xb9\xdb\x1atL\x92" +
	"\x01`\x19\xc22\xd8\xb4.3I6.\xeb\x83\xd4\xae" +
	"\x1bV\xc7\xcf\xff_\xa7\xe54g\xd7\x0b\x05gB\xa1" +
	"\x1fSR\xd45a\xdd/0g\x08a\x08\xfe\x0e\x00" +
	"\x00\xff\xff\xc3z\x9c^"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b0c0debaadc0deb0,
		Nodes: []uint64{
			0xb15cd2b768ffe71c,
			0xb70d94b5bbba004a,
			0xd0d235685d85719f,
			0xec0494688f0a29ca,
		},
		Compressed: true,
	})
}
