// Code generated by capnpc-go. DO NOT EDIT.

package ast

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type AstNode capnp.Struct

// AstNode_TypeID is the unique identifier for the type AstNode.
const AstNode_TypeID = 0xb24b3ac260166fdd

func NewAstNode(s *capnp.Segment) (AstNode, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return AstNode(st), err
}

func NewRootAstNode(s *capnp.Segment) (AstNode, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return AstNode(st), err
}

func ReadRootAstNode(msg *capnp.Message) (AstNode, error) {
	root, err := msg.Root()
	return AstNode(root.Struct()), err
}

func (s AstNode) String() string {
	str, _ := text.Marshal(0xb24b3ac260166fdd, capnp.Struct(s))
	return str
}

func (s AstNode) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AstNode) DecodeFromPtr(p capnp.Ptr) AstNode {
	return AstNode(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AstNode) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AstNode) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AstNode) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AstNode) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AstNode) NodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AstNode) HasNodeId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AstNode) NodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AstNode) SetNodeId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AstNode) SourceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AstNode) HasSourceId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AstNode) SourceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AstNode) SetSourceId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AstNode) NodeKind() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AstNode) HasNodeKind() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AstNode) NodeKindBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AstNode) SetNodeKind(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AstNode) Range() (common.Range, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return common.Range(p.Struct()), err
}

func (s AstNode) HasRange() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AstNode) SetRange(v common.Range) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewRange sets the range field to a newly
// allocated common.Range struct, preferring placement in s's segment.
func (s AstNode) NewRange() (common.Range, error) {
	ss, err := common.NewRange(capnp.Struct(s).Segment())
	if err != nil {
		return common.Range{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AstNode_List is a list of AstNode.
type AstNode_List = capnp.StructList[AstNode]

// NewAstNode creates a new list of AstNode.
func NewAstNode_List(s *capnp.Segment, sz int32) (AstNode_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[AstNode](l), err
}

// AstNode_Future is a wrapper for a AstNode promised by a client call.
type AstNode_Future struct{ *capnp.Future }

func (f AstNode_Future) Struct() (AstNode, error) {
	p, err := f.Future.Ptr()
	return AstNode(p.Struct()), err
}
func (p AstNode_Future) Range() common.Range_Future {
	return common.Range_Future{Future: p.Future.Field(3, nil)}
}

const schema_9e1e4e1af2b578d9 = "x\xdaL\xca\xb1J\xc3P\x14\xc6\xf1\xef;'U\x90" +
	"\x16rippP\x9f@\xd01\x8b:\xa6\xc5\xe0\xd9" +
	"\x1d\x0c\xbd\x17\x154\x09M\x0b\x1d|\x0aq\x16|\x05" +
	"!\x08\xba\xb9\xf8\x0c\x0e\xce\xee\xee\x12\xc9\"n\x7f~" +
	"\xfc\xe3\xc7\xa3h\x7f\xf4.\x10\xdb\x1d\xacu\x9f\xd5\xe6" +
	"\xf9[:}\x82\xdb`\xf7\xb1j\xbf\xb7\xf2\xed\x07\x0c" +
	"\xa2u`\x9c\xf1nl\xec\xeb\x84_\xc8\xbb\xa2Y\xec" +
	"\xcd\x8a\xbad\x9d\x1e7\x8b\xbc\xf2\x0c\xa7\xa4\xc5\x1a\x01" +
	"\x11\x01W\xa4\x80\x9d)\xedR\xe8\xc8\x84=\x86\x09`" +
	"^i\xb5\xd0\x89$\x14\xc0\xdd\xf4x\xad\xb4\x95\xd0\xa9" +
	"&T\xc0-\x0f\x00\xab\x95v+<,+\x1f2\xcf" +
	"!\x84C\xb0k\xaa\xe5|\x162\x0f\xe0\xcf\xfaez" +
	"U\xfe\xb7\x9dyQ^\x04\xc6?\x93\x97\xd7\xf6~\xf4" +
	"\x0c2\x06\x7f\x03\x00\x00\xff\xff\xd3\xc33\x83"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_9e1e4e1af2b578d9,
		Nodes: []uint64{
			0xb24b3ac260166fdd,
		},
		Compressed: true,
	})
}
