// IR → Go source.
//
// Phase 1 v1 (cloister-75f6d5): types + json tags only. Canonical
// encoders (MarshalJSON / MarshalCBOR matching capnp's wire shape)
// land in cloister-765d83 (v2). Until then, the default Go JSON
// encoder produces something close-but-not-identical to capnp's
// JSON convention for unions — bead D's round-trip gate will surface
// the gap and C will close it.
//
// Mirrors `outputs/zod.rs` in shape:
//   - struct → exported Go struct with json tags
//   - enum   → typed string + const block per variant
//   - union  → nested `<Struct><Discriminant>Union` struct with
//              `*Variant` `omitempty` pointer fields, one per variant
//   - lists  → `[]T`
//   - consts → typed const (scalar) or var (list/struct)
//
// Naming:
//   - capnp `someField` → Go `SomeField` (first-letter PascalCase;
//     deliberately NOT renaming acronym sequences à la golint
//     `HTTPForward` — keeping a deterministic mapping that round-
//     trips through the JSON tag, which preserves the wire name).
//   - struct/enum names are already PascalCase from capnp; pass
//     through unchanged.
//   - union helper type: `<Struct><Discriminant>Union` (e.g.
//     `BackendKindUnion`).

use std::fmt::Write as _;

use crate::error::Result;
use crate::ir::{Const, ConstValue, Enum, FieldType, ScalarType, Schema, Struct, Union};

pub fn emit(schema: &Schema, package_name: &str) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "// Generated by schema-bridge — do not edit by hand.")
        .expect("write! to String is infallible");
    writeln!(
        out,
        "// Regenerate with `task cluster:go` (runs the schema-bridge plugin)."
    )
    .expect("write! to String is infallible");
    writeln!(out, "//").expect("write! to String is infallible");
    writeln!(out, "// If schema-bridge errored on a construct used here,")
        .expect("write! to String is infallible");
    writeln!(out, "// the codegen needs a new mapping — extend it, don't")
        .expect("write! to String is infallible");
    writeln!(out, "// hand-author this file.").expect("write! to String is infallible");
    writeln!(out).expect("write! to String is infallible");
    writeln!(out, "package {package_name}").expect("write! to String is infallible");
    writeln!(out).expect("write! to String is infallible");

    // Custom MarshalJSON/UnmarshalJSON for void-variant unions need
    // the encoding/json package. Other emitters never call it
    // explicitly (the default Go JSON encoder is invoked at use site,
    // not from the generated file).
    if schema_needs_json_import(schema) {
        writeln!(out, r#"import "encoding/json""#).expect("write! to String is infallible");
        writeln!(out).expect("write! to String is infallible");
    }

    // Enums first: pure value types, no forward references.
    for e in &schema.enums {
        emit_enum(&mut out, e);
        writeln!(out).expect("write! to String is infallible");
    }

    // Structs and their union helper types. Go has no forward-
    // declaration concern — types may reference each other in any
    // file order within the same package.
    for s in &schema.structs {
        emit_struct(&mut out, s)?;
        writeln!(out).expect("write! to String is infallible");
    }

    // Consts last so they can reference enum / struct names declared
    // above.
    for c in &schema.consts {
        emit_const(&mut out, c);
        writeln!(out).expect("write! to String is infallible");
    }

    Ok(out)
}

// True iff any struct in the schema has a union with at least one
// Void variant — those structs need custom Marshal/UnmarshalJSON
// methods to encode Void as `null` instead of `{}`. Per cloister-765d83.
fn schema_needs_json_import(schema: &Schema) -> bool {
    schema
        .structs
        .iter()
        .any(|s| s.union.as_ref().is_some_and(union_has_void_variant))
}

fn union_has_void_variant(u: &Union) -> bool {
    u.variants
        .iter()
        .any(|v| matches!(v.ty, FieldType::Scalar(ScalarType::Void)))
}

fn emit_enum(out: &mut String, e: &Enum) {
    // Blank line between `type X string` and `const (…)` matches
    // gofmt — the rest of gofmt's alignment work (column padding
    // within const/struct blocks) is delegated to gofmt itself in
    // `task cluster:go`'s pipeline.
    writeln!(out, "type {name} string", name = e.name).expect("write! to String is infallible");
    writeln!(out).expect("write! to String is infallible");
    writeln!(out, "const (").expect("write! to String is infallible");
    for v in &e.variants {
        // EnumName + PascalCase(variant) — e.g. `TierHypervisor Tier
        // = "hypervisor"`. Variant value preserves capnp's wire
        // string verbatim.
        writeln!(
            out,
            "\t{enum}{cap} {enum} = \"{wire}\"",
            enum = e.name,
            cap = pascal_case(v),
            wire = v
        )
        .expect("write! to String is infallible");
    }
    writeln!(out, ")").expect("write! to String is infallible");
}

fn emit_struct(out: &mut String, s: &Struct) -> Result<()> {
    // Named-group unions get a helper type emitted first so the struct
    // field referencing it reads top-down. Anonymous-inline unions
    // inline their variants directly into the parent struct as
    // omitempty pointer fields — no helper type needed.
    let named_union = s.union.as_ref().filter(|u| u.discriminant_name.is_some());
    if let Some(u) = named_union {
        emit_union_type(out, &s.name, u);
        writeln!(out).expect("write! to String is infallible");
        // Custom marshalers when at least one variant is Void.
        // Default Go json encoding of `*struct{}` (non-nil) is `{}`,
        // but capnp's JSON convention is `null` for the void payload.
        // Custom (Un)MarshalJSON closes that gap so Go ↔ JSON ↔ Go
        // round-trips don't lose the variant selection. Per
        // cloister-765d83 / ADR-0036 Phase 1 piece C.
        if union_has_void_variant(u) {
            let union_name = union_type_name(
                &s.name,
                u.discriminant_name.as_deref().expect("named union"),
            );
            emit_union_void_marshalers(out, &union_name, u);
            writeln!(out).expect("write! to String is infallible");
        }
    }

    writeln!(out, "type {name} struct {{", name = s.name).expect("write! to String is infallible");
    for field in &s.fields {
        writeln!(
            out,
            "\t{field_name} {ty} `json:\"{wire}\"`",
            field_name = pascal_case(&field.name),
            ty = render_go_type(&field.ty),
            wire = field.name
        )
        .expect("write! to String is infallible");
    }
    if let Some(u) = &s.union {
        match &u.discriminant_name {
            Some(disc) => {
                // Named-group union: nested helper type, JSON nests
                // the variant under the discriminant key.
                writeln!(
                    out,
                    "\t{field_name} {union_ty} `json:\"{wire}\"`",
                    field_name = pascal_case(disc),
                    union_ty = union_type_name(&s.name, disc),
                    wire = disc
                )
                .expect("write! to String is infallible");
            }
            None => {
                // Anonymous-inline union: variants encode flat as
                // siblings of base fields. Each variant emits as a
                // `*T` field with `omitempty` so the marshaler emits
                // only the populated branch. Void variants emit as
                // `*struct{}` (same shape as the named case; precise
                // JSON-null encoding is bead C's job).
                for variant in &u.variants {
                    let ty = match &variant.ty {
                        FieldType::Scalar(ScalarType::Void) => "*struct{}".to_owned(),
                        FieldType::StructRef(name) => format!("*{name}"),
                        other => format!("*{}", render_go_type(other)),
                    };
                    writeln!(
                        out,
                        "\t{field_name} {ty} `json:\"{wire},omitempty\"`",
                        field_name = pascal_case(&variant.name),
                        wire = variant.name
                    )
                    .expect("write! to String is infallible");
                }
            }
        }
    }
    writeln!(out, "}}").expect("write! to String is infallible");
    Ok(())
}

// Emit the helper struct for a union — one nullable pointer per
// variant, with `omitempty` so the marshaler emits only the populated
// branch. Void variants type as `*struct{}`; their precise JSON
// encoding (capnp's convention is `null`) is bead C's job. For v1 the
// default encoder produces `{}` for a non-nil empty struct, which
// round-trips imperfectly until C lands; D will catch the divergence.
fn emit_union_type(out: &mut String, struct_name: &str, u: &Union) {
    // emit_union_type is only invoked for named-group unions
    // (anonymous-inline emit inlines variants into the parent struct
    // directly), so discriminant_name is guaranteed Some here.
    let disc = u
        .discriminant_name
        .as_deref()
        .expect("emit_union_type called with anonymous-inline union");
    let union_name = union_type_name(struct_name, disc);
    writeln!(out, "type {union_name} struct {{").expect("write! to String is infallible");
    for variant in &u.variants {
        let ty = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "*struct{}".to_owned(),
            FieldType::StructRef(name) => format!("*{name}"),
            other => format!("*{}", render_go_type(other)),
        };
        writeln!(
            out,
            "\t{field_name} {ty} `json:\"{wire},omitempty\"`",
            field_name = pascal_case(&variant.name),
            wire = variant.name
        )
        .expect("write! to String is infallible");
    }
    writeln!(out, "}}").expect("write! to String is infallible");
}

// Custom (Un)MarshalJSON for a union type containing Void variants.
// Without these, `*struct{}` would marshal to `{}` instead of capnp's
// canonical `null`, AND unmarshaling `null` would clear the pointer
// (losing the variant selection). The generated marshalers preserve
// both directions:
//
//   - Marshal: each non-nil variant emits as `{"name": payload}` or
//     `{"name": null}` for Void. Mutually exclusive: the first
//     non-nil pointer wins; subsequent ones are silently ignored
//     since a union has exactly one set variant by capnp wire spec.
//   - Unmarshal: KEY PRESENCE (regardless of value) selects the
//     variant. For Void variants, the key being present at all sets
//     the pointer to `&struct{}{}`. For payload variants, the key's
//     value is unmarshaled into the variant type.
//
// Per cloister-765d83.
fn emit_union_void_marshalers(out: &mut String, union_name: &str, u: &Union) {
    // MarshalJSON.
    writeln!(
        out,
        "func (u {union_name}) MarshalJSON() ([]byte, error) {{"
    )
    .expect("write! to String is infallible");
    for variant in &u.variants {
        let field = pascal_case(&variant.name);
        match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => {
                // Void variant: emit literal `{"name":null}`. The
                // value is intentionally null (not omitted) to match
                // capnp's JSON convention.
                writeln!(
                    out,
                    "\tif u.{field} != nil {{ return []byte(`{{\"{wire}\":null}}`), nil }}",
                    wire = variant.name
                )
                .expect("write! to String is infallible");
            }
            _ => {
                // Payload variant: delegate to json.Marshal of a
                // single-key map. Quoting through a map avoids
                // having to escape the wire name into a printf
                // template.
                writeln!(
                    out,
                    "\tif u.{field} != nil {{ return json.Marshal(map[string]any{{\"{wire}\": u.{field}}}) }}",
                    wire = variant.name
                )
                .expect("write! to String is infallible");
            }
        }
    }
    // No variant set — emit `{}`. Callers shouldn't reach this; capnp
    // unions always have exactly one variant. The empty-object
    // fallback is safer than nil/error: downstream consumers can still
    // unmarshal it (all-nil result), surfacing the bug at the
    // construction site rather than here.
    writeln!(out, "\treturn []byte(`{{}}`), nil").expect("write! to String is infallible");
    writeln!(out, "}}").expect("write! to String is infallible");
    writeln!(out).expect("write! to String is infallible");

    // UnmarshalJSON.
    writeln!(
        out,
        "func (u *{union_name}) UnmarshalJSON(data []byte) error {{"
    )
    .expect("write! to String is infallible");
    writeln!(out, "\tvar raw map[string]json.RawMessage").expect("write! to String is infallible");
    writeln!(
        out,
        "\tif err := json.Unmarshal(data, &raw); err != nil {{ return err }}"
    )
    .expect("write! to String is infallible");
    for variant in &u.variants {
        let field = pascal_case(&variant.name);
        match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => {
                // Key presence selects the variant. Value is null per
                // capnp's convention; we don't decode it.
                writeln!(
                    out,
                    "\tif _, ok := raw[\"{wire}\"]; ok {{ u.{field} = &struct{{}}{{}} }}",
                    wire = variant.name
                )
                .expect("write! to String is infallible");
            }
            FieldType::StructRef(name) => {
                writeln!(
                    out,
                    "\tif msg, ok := raw[\"{wire}\"]; ok {{ u.{field} = &{name}{{}}; if err := json.Unmarshal(msg, u.{field}); err != nil {{ return err }} }}",
                    wire = variant.name
                )
                .expect("write! to String is infallible");
            }
            other => {
                // Scalars, lists, enum refs — decode through the
                // generic FieldType's Go form. Allocate a new value of
                // the right type and unmarshal into it.
                let ty = render_go_type(other);
                writeln!(
                    out,
                    "\tif msg, ok := raw[\"{wire}\"]; ok {{ var v {ty}; if err := json.Unmarshal(msg, &v); err != nil {{ return err }}; u.{field} = &v }}",
                    wire = variant.name
                )
                .expect("write! to String is infallible");
            }
        }
    }
    writeln!(out, "\treturn nil").expect("write! to String is infallible");
    writeln!(out, "}}").expect("write! to String is infallible");
}

fn render_go_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_go_scalar(*s).to_owned(),
        FieldType::StructRef(name) => name.clone(),
        FieldType::EnumRef(name) => name.clone(),
        FieldType::List(inner) => format!("[]{}", render_go_type(inner)),
    }
}

fn render_go_scalar(s: ScalarType) -> &'static str {
    match s {
        // Void appears only at union-variant level in our schemas;
        // see emit_union_type which handles the Void special case.
        // Reaching this arm at field level would mean someone declared
        // a `Void` typed STRUCT field, which capnp permits but is
        // pointless — emit `struct{}` so the build still compiles and
        // a future schema using it lights up at use site.
        ScalarType::Void => "struct{}",
        ScalarType::Bool => "bool",
        ScalarType::Int8 => "int8",
        ScalarType::Int16 => "int16",
        ScalarType::Int32 => "int32",
        ScalarType::Int64 => "int64",
        ScalarType::UInt8 => "uint8",
        ScalarType::UInt16 => "uint16",
        ScalarType::UInt32 => "uint32",
        ScalarType::UInt64 => "uint64",
        ScalarType::Float32 => "float32",
        ScalarType::Float64 => "float64",
        ScalarType::Text => "string",
        ScalarType::Data => "[]byte",
    }
}

fn emit_const(out: &mut String, c: &Const) {
    let name = pascal_case(&c.name);
    match &c.value {
        // Scalar consts → `const Name <type> = <literal>`. The typed
        // form preserves the schema's declared width (Int32 vs Int64)
        // rather than letting Go infer an untyped constant kind.
        ConstValue::Bool(b) => {
            writeln!(out, "const {name} {ty} = {b}", ty = render_go_type(&c.ty))
                .expect("write! to String is infallible");
        }
        ConstValue::Int(n) => {
            writeln!(out, "const {name} {ty} = {n}", ty = render_go_type(&c.ty))
                .expect("write! to String is infallible");
        }
        ConstValue::UInt(n) => {
            writeln!(out, "const {name} {ty} = {n}", ty = render_go_type(&c.ty))
                .expect("write! to String is infallible");
        }
        ConstValue::Float(f) => {
            writeln!(
                out,
                "const {name} {ty} = {lit}",
                ty = render_go_type(&c.ty),
                lit = render_go_float_literal(*f)
            )
            .expect("write! to String is infallible");
        }
        ConstValue::Text(s) => {
            writeln!(
                out,
                "const {name} string = \"{esc}\"",
                esc = escape_go_string(s)
            )
            .expect("write! to String is infallible");
        }
        ConstValue::Enum(variant) => {
            // Enum consts emit as the prefixed constant declared in
            // emit_enum — `var ColorBlue = ColorBlue` would self-
            // reference; instead emit `const X Color = ColorBlue`
            // pointing at the enum constant for the variant.
            writeln!(
                out,
                "const {name} {ty} = {ty}{cap}",
                ty = render_go_type(&c.ty),
                cap = pascal_case(variant)
            )
            .expect("write! to String is infallible");
        }
        // Composite values can't be Go `const`s (they aren't basic
        // kinds) so render as `var`. The type is required because
        // untyped literals widen unpredictably.
        ConstValue::List(items) => {
            let inner_ty = match &c.ty {
                FieldType::List(t) => render_go_type(t),
                // Defensive: const declared as List but ConstValue
                // shape is List too — fall back to the outer type.
                other => render_go_type(other),
            };
            let elems: Vec<String> = items.iter().map(render_const_value).collect();
            writeln!(
                out,
                "var {name} = []{inner_ty}{{{joined}}}",
                joined = elems.join(", ")
            )
            .expect("write! to String is infallible");
        }
        ConstValue::Struct(fields) => {
            let inner: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}: {v}", k = pascal_case(k), v = render_const_value(v)))
                .collect();
            writeln!(
                out,
                "var {name} = {ty}{{{joined}}}",
                ty = render_go_type(&c.ty),
                joined = inner.join(", ")
            )
            .expect("write! to String is infallible");
        }
        ConstValue::Void => {
            // `Void` consts aren't a real cloister pattern. Emit a
            // typed-nil placeholder so the build still compiles if
            // one slips through; surfaces at use site rather than
            // here.
            writeln!(out, "var {name} struct{{}}").expect("write! to String is infallible");
        }
    }
}

fn render_const_value(v: &ConstValue) -> String {
    match v {
        ConstValue::Void => "struct{}{}".to_owned(),
        ConstValue::Bool(b) => b.to_string(),
        ConstValue::Int(n) => n.to_string(),
        ConstValue::UInt(n) => n.to_string(),
        ConstValue::Float(f) => render_go_float_literal(*f),
        ConstValue::Text(s) => format!("\"{}\"", escape_go_string(s)),
        ConstValue::Enum(variant) => pascal_case(variant), // bare; caller prefixes type
        ConstValue::List(items) => {
            let inner: Vec<String> = items.iter().map(render_const_value).collect();
            format!("{{{}}}", inner.join(", "))
        }
        ConstValue::Struct(fields) => {
            let inner: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}: {v}", k = pascal_case(k), v = render_const_value(v)))
                .collect();
            format!("{{{}}}", inner.join(", "))
        }
    }
}

// Go float literal must keep a decimal point or exponent, otherwise
// the parser treats `1` as an untyped int constant. Inf/NaN aren't
// representable as Go literals — emit `math.NaN()` style would
// require an import; surface a typed sentinel that breaks the build
// rather than emitting silently-wrong code.
fn render_go_float_literal(f: f64) -> String {
    if !f.is_finite() {
        // Mirror the zod emitter's strategy: visible build break.
        return format!("/* unrepresentable float: {f} */ 0.0");
    }
    let s = format!("{f}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

fn escape_go_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

fn union_type_name(struct_name: &str, discriminant_name: &str) -> String {
    format!("{struct_name}{}Union", pascal_case(discriminant_name))
}

// camelCase → PascalCase by uppercasing the first ASCII letter.
// Subsequent characters pass through unchanged — no acronym
// normalization (golint-style HTTP/URL/ID heuristics would couple
// the emitter to a stylistic preference that's downstream's call,
// not the codegen's). Capnp identifiers are ASCII-only by spec
// (§5.3 "Capnp Schema Files"), so byte-level slicing is safe.
fn pascal_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => {
            let mut out = String::with_capacity(s.len());
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
            out
        }
    }
}
