// IR → JSON Schema draft 2020-12.
//
// Third output format (ley-line-open-6585aa). First consumer is
// rosary's MCP tool registry (rosary-08a278): MCP `inputSchema` is a
// draft 2020-12 object schema, so each capnp struct lands as a
// `$defs` entry (`type`/`properties`/`required`) a consumer can pluck
// verbatim into a `tools/list` response.
//
// One document per schema file:
//
//   {
//     "$schema": "https://json-schema.org/draft/2020-12/schema",
//     "$comment": "Generated by schema-bridge — do not edit by hand.",
//     "$id": "<basename>.schema.json",
//     "$defs": { <enums>, <structs>, <consts> }
//   }
//
// Mapping semantics mirror the zod emitter (`outputs/zod.rs`):
//   - struct → object schema; ALL fields required (capnp has no
//     optional fields — a field always has a value on the wire);
//     `additionalProperties: false` mirrors zod's `.strict()` so an
//     operator typo is a validation error, not silently-dropped data
//     (cloister-cf2e6a).
//   - named-group union (`kind :union { … }`) → the discriminant
//     property is a `oneOf` of single-key branch objects, matching
//     capnp's nested JSON convention (`"kind": {"durableObject": …}`).
//     Void variant payloads are `{"type":"null"}` (capnp encodes the
//     void payload as JSON `null`).
//   - anonymous-inline union (`struct Foo { union { … } }`) → the
//     whole struct def is a `oneOf` whose branches inline the base
//     fields plus exactly one variant key — the flat encoding, per
//     cloister-77172d. `oneOf` (not `anyOf`) because capnp's wire
//     discriminant selects exactly one variant.
//   - Data → `{"type":"string","contentEncoding":"base64"}` — the
//     wire-JSON view (Go's encoding/json base64-encodes []byte).
//     zod's `z.instanceof(Uint8Array)` validates the decoded
//     in-memory value instead; the emitters already diverge on Data's
//     runtime representation, and this emitter describes wire text.
//   - const → `{"const": <value>}` $defs entry. Non-finite float
//     consts are a hard error: zod/go emit a visible build-break
//     sentinel, but JSON text has no sentinel that stays valid JSON.
//   - no `description` fields: capnp's CodeGeneratorRequest carries
//     no doc comments (capnp discards comments at parse), so there is
//     nothing to map — descriptions arrive later via an annotation
//     vocabulary, not invented here.
//
// Determinism: output is built by direct string emission in IR
// declaration order (enums, structs, consts — same order as zod/go).
// No map-keyed serialization anywhere, so key order is stable across
// runs by construction.

use std::fmt::Write as _;

use crate::error::{Result, SchemaBridgeError};
use crate::ir::{Const, ConstValue, Enum, FieldType, ScalarType, Schema, Struct, Union};

pub fn emit(schema: &Schema, schema_basename: &str) -> Result<String> {
    let mut defs: Vec<String> = Vec::new();
    // Enums first, then structs, then consts — the zod/go declaration
    // order, kept identical so cross-emitter diffs line up.
    for e in &schema.enums {
        defs.push(render_enum_def(e));
    }
    for s in &schema.structs {
        defs.push(render_struct_def(s));
    }
    for c in &schema.consts {
        defs.push(render_const_def(c)?);
    }

    let mut out = String::new();
    writeln!(out, "{{").expect("write! to String is infallible");
    writeln!(
        out,
        r#"  "$schema": "https://json-schema.org/draft/2020-12/schema","#
    )
    .expect("write! to String is infallible");
    // JSON has no comment syntax; draft 2020-12's `$comment` keyword
    // carries the do-not-edit header the zod/go emitters put in `//`
    // lines.
    writeln!(
        out,
        r#"  "$comment": "Generated by schema-bridge — do not edit by hand.","#
    )
    .expect("write! to String is infallible");
    writeln!(
        out,
        r#"  "$id": "{}.schema.json","#,
        escape_json_string(schema_basename)
    )
    .expect("write! to String is infallible");
    if defs.is_empty() {
        writeln!(out, r#"  "$defs": {{}}"#).expect("write! to String is infallible");
    } else {
        writeln!(out, r#"  "$defs": {{"#).expect("write! to String is infallible");
        out.push_str(&defs.join(",\n"));
        out.push('\n');
        writeln!(out, "  }}").expect("write! to String is infallible");
    }
    writeln!(out, "}}").expect("write! to String is infallible");
    Ok(out)
}

// `"Tier": { "type": "string", "enum": ["hypervisor", "cluster"] }` —
// enum values are capnp's wire strings in ordinal order, matching the
// zod `z.enum([…])` and Go const-block emit.
fn render_enum_def(e: &Enum) -> String {
    let values: Vec<String> = e
        .variants
        .iter()
        .map(|v| format!("\"{}\"", escape_json_string(v)))
        .collect();
    format!(
        r#"    "{name}": {{ "type": "string", "enum": [{values}] }}"#,
        name = escape_json_string(&e.name),
        values = values.join(", ")
    )
}

fn render_struct_def(s: &Struct) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "    \"{name}\": {{",
        name = escape_json_string(&s.name)
    )
    .expect("write! to String is infallible");

    match &s.union {
        // Anonymous-inline union: the whole def is a oneOf over flat
        // branches (base fields + exactly one variant key each).
        Some(u) if u.discriminant_name.is_none() => {
            writeln!(out, r#"      "oneOf": ["#).expect("write! to String is infallible");
            let branches: Vec<String> = u
                .variants
                .iter()
                .map(|v| {
                    let mut props: Vec<(String, String)> = s
                        .fields
                        .iter()
                        .map(|f| (f.name.clone(), render_type(&f.ty)))
                        .collect();
                    props.push((v.name.clone(), render_variant_payload(v)));
                    format!("        {}", render_inline_object(&props))
                })
                .collect();
            out.push_str(&branches.join(",\n"));
            out.push('\n');
            writeln!(out, "      ]").expect("write! to String is infallible");
        }
        // Plain struct or named-group union: one object schema; the
        // union (if any) is a oneOf-typed property named after the
        // discriminant, required like any base field.
        union => {
            let disc = union.as_ref().map(|u| {
                u.discriminant_name
                    .as_deref()
                    .expect("anonymous-inline unions route to the oneOf arm above")
            });
            writeln!(out, r#"      "type": "object","#).expect("write! to String is infallible");
            let mut props: Vec<String> = s
                .fields
                .iter()
                .map(|f| {
                    format!(
                        "        \"{name}\": {ty}",
                        name = escape_json_string(&f.name),
                        ty = render_type(&f.ty)
                    )
                })
                .collect();
            if let (Some(u), Some(disc)) = (union, disc) {
                props.push(render_named_union_property(disc, u));
            }
            if props.is_empty() {
                writeln!(out, r#"      "properties": {{}},"#)
                    .expect("write! to String is infallible");
            } else {
                writeln!(out, r#"      "properties": {{"#).expect("write! to String is infallible");
                out.push_str(&props.join(",\n"));
                out.push('\n');
                writeln!(out, "      }},").expect("write! to String is infallible");
            }
            let required: Vec<String> = s
                .fields
                .iter()
                .map(|f| f.name.as_str())
                .chain(disc)
                .map(|n| format!("\"{}\"", escape_json_string(n)))
                .collect();
            writeln!(out, r#"      "required": [{}],"#, required.join(", "))
                .expect("write! to String is infallible");
            writeln!(out, r#"      "additionalProperties": false"#)
                .expect("write! to String is infallible");
        }
    }

    write!(out, "    }}").expect("write! to String is infallible");
    out
}

// The named-union discriminant property: a oneOf of single-key strict
// branch objects, one per variant — the nested JSON convention
// (`"kind": {"durableObject": {…}}`).
fn render_named_union_property(disc: &str, u: &Union) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "        \"{disc}\": {{",
        disc = escape_json_string(disc)
    )
    .expect("write! to String is infallible");
    writeln!(out, r#"          "oneOf": ["#).expect("write! to String is infallible");
    let branches: Vec<String> = u
        .variants
        .iter()
        .map(|v| {
            let props = vec![(v.name.clone(), render_variant_payload(v))];
            format!("            {}", render_inline_object(&props))
        })
        .collect();
    out.push_str(&branches.join(",\n"));
    out.push('\n');
    writeln!(out, "          ]").expect("write! to String is infallible");
    write!(out, "        }}").expect("write! to String is infallible");
    out
}

// A single-line strict object schema over the given (name, rendered
// type-schema) pairs — the branch shape shared by both union forms.
fn render_inline_object(props: &[(String, String)]) -> String {
    let rendered_props: Vec<String> = props
        .iter()
        .map(|(name, ty)| format!("\"{}\": {ty}", escape_json_string(name)))
        .collect();
    let required: Vec<String> = props
        .iter()
        .map(|(name, _)| format!("\"{}\"", escape_json_string(name)))
        .collect();
    format!(
        r#"{{ "type": "object", "properties": {{ {props} }}, "required": [{required}], "additionalProperties": false }}"#,
        props = rendered_props.join(", "),
        required = required.join(", ")
    )
}

// Void union variants carry no payload; capnp's JSON convention
// encodes the selected variant as `null` (`{"uds": null}`), so the
// payload schema is `{"type":"null"}` — the mirror of zod's
// `z.null()` for the same position.
fn render_variant_payload(v: &crate::ir::UnionVariant) -> String {
    match &v.ty {
        FieldType::Scalar(ScalarType::Void) => r#"{ "type": "null" }"#.to_owned(),
        other => render_type(other),
    }
}

// Single-line type schema for a field position. Recursion depth is
// bounded by the IR (lists nest; unions can't appear here).
fn render_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_scalar(*s).to_owned(),
        // Struct and enum refs both resolve within this document —
        // schema-bridge only processes one capnp file per invocation,
        // so every referent has a $defs entry (the parser fails on
        // unresolved references before emit runs).
        FieldType::StructRef(name) | FieldType::EnumRef(name) => {
            format!(r##"{{ "$ref": "#/$defs/{}" }}"##, escape_json_string(name))
        }
        FieldType::List(inner) => {
            format!(r#"{{ "type": "array", "items": {} }}"#, render_type(inner))
        }
    }
}

fn render_scalar(s: ScalarType) -> &'static str {
    match s {
        // Bare Void fields (outside unions) are `null` in capnp's
        // JSON encoding, same as Void union payloads.
        ScalarType::Void => r#"{ "type": "null" }"#,
        ScalarType::Bool => r#"{ "type": "boolean" }"#,
        // All signed widths collapse to `integer` — same collapse the
        // zod emitter makes (`z.number().int()`); the capnp schema
        // remains the authority on width. 64-bit values above 2^53
        // lose precision in any JSON number pipeline; that constraint
        // is capnp-JSON's, not this emitter's.
        ScalarType::Int8 | ScalarType::Int16 | ScalarType::Int32 | ScalarType::Int64 => {
            r#"{ "type": "integer" }"#
        }
        // Unsigned adds `minimum: 0`, mirroring zod's `.nonnegative()`.
        ScalarType::UInt8 | ScalarType::UInt16 | ScalarType::UInt32 | ScalarType::UInt64 => {
            r#"{ "type": "integer", "minimum": 0 }"#
        }
        ScalarType::Float32 | ScalarType::Float64 => r#"{ "type": "number" }"#,
        ScalarType::Text => r#"{ "type": "string" }"#,
        ScalarType::Data => r#"{ "type": "string", "contentEncoding": "base64" }"#,
    }
}

// `"name": { "const": <value> }` — draft 2020-12's `const` keyword is
// the value-pinning counterpart of zod's `as const` emit.
fn render_const_def(c: &Const) -> Result<String> {
    Ok(format!(
        r#"    "{name}": {{ "const": {value} }}"#,
        name = escape_json_string(&c.name),
        value = render_const_value(&c.value, &c.name)?
    ))
}

fn render_const_value(v: &ConstValue, location: &str) -> Result<String> {
    Ok(match v {
        ConstValue::Void => "null".to_owned(),
        ConstValue::Bool(b) => b.to_string(),
        ConstValue::Int(n) => n.to_string(),
        ConstValue::UInt(n) => n.to_string(),
        ConstValue::Float(f) => {
            // JSON has no Inf/NaN literal. zod/go emit a visible
            // build-break sentinel; JSON text has no sentinel that
            // stays valid JSON, so fail loudly instead — the crate's
            // "every gap is loud" invariant.
            if !f.is_finite() {
                return Err(SchemaBridgeError::unmapped(
                    "non-finite float const value",
                    location,
                ));
            }
            // Rust's default f64 Display always produces a valid JSON
            // number for finite values (`1` for 1.0 is legal JSON).
            format!("{f}")
        }
        ConstValue::Text(s) => format!("\"{}\"", escape_json_string(s)),
        // Enum consts pin the wire string, matching the zod emit and
        // the `enum` arrays in $defs.
        ConstValue::Enum(name) => format!("\"{}\"", escape_json_string(name)),
        ConstValue::List(items) => {
            let inner: Result<Vec<String>> = items
                .iter()
                .map(|i| render_const_value(i, location))
                .collect();
            format!("[{}]", inner?.join(", "))
        }
        // Declaration-order pairs from the IR — deterministic without
        // re-consulting the struct schema.
        ConstValue::Struct(fields) => {
            let inner: Result<Vec<String>> = fields
                .iter()
                .map(|(k, v)| {
                    Ok(format!(
                        "\"{}\": {}",
                        escape_json_string(k),
                        render_const_value(v, location)?
                    ))
                })
                .collect();
            format!("{{ {} }}", inner?.join(", "))
        }
    })
}

// RFC 8259 string escape: backslash, quote, and all control chars
// (named escapes where they exist, \u00XX otherwise). Capnp Text is
// UTF-8; non-control characters pass through verbatim.
fn escape_json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{08}' => out.push_str("\\b"),
            '\u{0C}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            other => out.push(other),
        }
    }
    out
}
