// IR → zod TypeScript source.
//
// Emits one zod schema per struct plus a TypeScript type alias derived
// from it. Struct-to-struct references resolve by name; topological
// order is enforced via forward-declaration via `z.lazy(...)`.

use std::fmt::Write as _;

use crate::error::Result;
use crate::ir::{
    Const, ConstValue, Enum, FieldType, ScalarType, Schema, Struct, StructField, Union,
};

pub fn emit(schema: &Schema) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "// Generated by schema-bridge — do not edit by hand.")
        .expect("write! to String is infallible");
    writeln!(
        out,
        "// Regenerate with `task cluster:zod` (runs the schema-bridge plugin)."
    )
    .expect("write! to String is infallible");
    writeln!(out, "//").expect("write! to String is infallible");
    writeln!(out, "// If schema-bridge errored on a construct used here,")
        .expect("write! to String is infallible");
    writeln!(out, "// the codegen needs a new mapping — extend it, don't")
        .expect("write! to String is infallible");
    writeln!(out, "// hand-author this file.").expect("write! to String is infallible");
    writeln!(out).expect("write! to String is infallible");
    writeln!(out, r#"import {{ z }} from "zod";"#).expect("write! to String is infallible");
    writeln!(out).expect("write! to String is infallible");

    // Enums emit first: no forward references possible (they only
    // reference string literals), and struct field renderers may
    // reference enum schema names.
    for e in &schema.enums {
        emit_enum(&mut out, e);
        writeln!(out).expect("write! to String is infallible");
    }

    for s in &schema.structs {
        emit_struct(&mut out, s)?;
        writeln!(out).expect("write! to String is infallible");
    }

    // Consts emit last so they can reference enum / struct names
    // declared above without forward-declaration. Each becomes a single
    // `export const NAME = <literal> as const;` line. Per cloister-946a59.
    for c in &schema.consts {
        emit_const(&mut out, c);
        writeln!(out).expect("write! to String is infallible");
    }

    Ok(out)
}

fn emit_enum(out: &mut String, e: &Enum) {
    let variants_zod: Vec<String> = e.variants.iter().map(|v| format!("\"{v}\"")).collect();
    let variants_ts: Vec<String> = e.variants.iter().map(|v| format!("\"{v}\"")).collect();
    writeln!(
        out,
        "export const {name}Schema = z.enum([{joined}]);",
        name = e.name,
        joined = variants_zod.join(", ")
    )
    .expect("write! to String is infallible");
    writeln!(
        out,
        "export type {name} = {joined};",
        name = e.name,
        joined = variants_ts.join(" | ")
    )
    .expect("write! to String is infallible");
}

fn emit_struct(out: &mut String, s: &Struct) -> Result<()> {
    // `z.lazy` lets struct refs forward-declare without a topological
    // sort. The cost is one extra closure per schema; the saving is
    // not having to detect cycles.
    writeln!(
        out,
        "export const {name}Schema: z.ZodType<{name}> = z.lazy(() =>",
        name = s.name
    )
    .expect("write! to String is infallible");

    match (&s.fields[..], &s.union) {
        // Plain struct: no union.
        (fields, None) => {
            emit_zod_object(out, "  ", fields, None);
            writeln!(out, ");").expect("write! to String is infallible");
        }
        // Struct with an anonymous-inline union (`struct Foo {
        // union { … } }`) — variants encode flat as siblings of base
        // fields. The whole schema is `z.union([variant-objects])`
        // where each variant-object carries base fields + exactly one
        // variant field.
        (fields, Some(u)) if u.discriminant_name.is_none() => {
            emit_zod_flat_union(out, "  ", fields, u);
            writeln!(out, ");").expect("write! to String is infallible");
        }
        // Struct with a named-group union — variants nest under the
        // discriminant name, matching capnp's JSON convention
        // (`"kind": { "external": {…} }` for struct variants,
        // `"transport": { "uds": null }` for Void variants). Base
        // fields are siblings of that nested object.
        (fields, Some(u)) => {
            emit_zod_object(out, "  ", fields, Some(u));
            writeln!(out, ");").expect("write! to String is infallible");
        }
    }
    writeln!(out).expect("write! to String is infallible");

    emit_ts_type(out, s);

    Ok(())
}

// Flat-union shape for anonymous-inline unions. JSON encoding has the
// variant field as a sibling of base fields (no discriminator
// wrapper), so the schema must accept any of N branches where each
// branch is `{ ...baseFields, oneVariant: T }.strict()`. Per
// cloister-77172d.
fn emit_zod_flat_union(out: &mut String, indent: &str, base_fields: &[StructField], u: &Union) {
    writeln!(out, "{indent}z.union([").expect("write! to String is infallible");
    for variant in &u.variants {
        let inner_indent = format!("{indent}  ");
        writeln!(out, "{inner_indent}z.object({{").expect("write! to String is infallible");
        for field in base_fields {
            writeln!(
                out,
                "{inner_indent}  {}: {},",
                field.name,
                render_field(field)
            )
            .expect("write! to String is infallible");
        }
        let variant_ty = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "z.null()".to_owned(),
            other => render_zod_type(other),
        };
        writeln!(out, "{inner_indent}  {}: {},", variant.name, variant_ty)
            .expect("write! to String is infallible");
        writeln!(out, "{inner_indent}}}).strict(),").expect("write! to String is infallible");
    }
    write!(out, "{indent}])").expect("write! to String is infallible");
}

// `.strict()` rejects unknown keys at parse time — without it, zod's
// default behavior silently drops them, so an operator typo like
// `holdsCredentials = ["SECRET"]` (extra 's' vs the schema's
// `holdsCredential`) discards the credential without a diagnostic.
// Per cloister-cf2e6a / skeptic N1: the schema-bridge is the boundary
// where typos must become errors. Inner union variants ALSO use
// `.strict()` (see `emit_zod_union` below).
fn emit_zod_object(out: &mut String, indent: &str, fields: &[StructField], union: Option<&Union>) {
    writeln!(out, "{indent}z.object({{").expect("write! to String is infallible");
    for field in fields {
        let rendered = render_field(field);
        writeln!(out, "{indent}  {}: {},", field.name, rendered)
            .expect("write! to String is infallible");
    }
    if let Some(u) = union {
        // emit_zod_object is only invoked for the named-group form
        // (the anonymous-inline form routes to emit_zod_flat_union),
        // so discriminant_name is guaranteed Some here.
        let disc = u
            .discriminant_name
            .as_deref()
            .expect("emit_zod_object called with anonymous-inline union — should route to emit_zod_flat_union");
        write!(out, "{indent}  {disc}: ").expect("write! to String is infallible");
        emit_zod_union(out, &format!("{indent}  "), u);
        writeln!(out, ",").expect("write! to String is infallible");
    }
    write!(out, "{indent}}}).strict()").expect("write! to String is infallible");
}

// Each variant is a single-key object. `z.union([...])` rather than
// `z.discriminatedUnion` because there's no discriminator field
// within the variant — the variant name IS the key. `.strict()`
// ensures each variant rejects keys belonging to its siblings, which
// is the runtime invariant that matches capnp's wire discriminant.
fn emit_zod_union(out: &mut String, indent: &str, u: &Union) {
    writeln!(out, "z.union([").expect("write! to String is infallible");
    for variant in &u.variants {
        let inner = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "z.null()".to_owned(),
            other => render_zod_type(other),
        };
        writeln!(
            out,
            "{indent}  z.object({{ {name}: {inner} }}).strict(),",
            name = variant.name
        )
        .expect("write! to String is infallible");
    }
    write!(out, "{indent}])").expect("write! to String is infallible");
}

fn emit_ts_type(out: &mut String, s: &Struct) {
    match (&s.fields[..], &s.union) {
        (fields, None) => {
            writeln!(out, "export interface {} {{", s.name)
                .expect("write! to String is infallible");
            for field in fields {
                writeln!(out, "  {}: {};", field.name, render_ts_type(&field.ty))
                    .expect("write! to String is infallible");
            }
            writeln!(out, "}}").expect("write! to String is infallible");
        }
        // Anonymous-inline union: a TS type alias (not interface),
        // since the runtime shape is a discriminated union over flat
        // objects. Each branch carries the base fields + exactly one
        // variant field.
        (fields, Some(u)) if u.discriminant_name.is_none() => {
            writeln!(
                out,
                "export type {} = {};",
                s.name,
                render_ts_flat_union(fields, u)
            )
            .expect("write! to String is infallible");
        }
        (fields, Some(u)) => {
            writeln!(out, "export interface {} {{", s.name)
                .expect("write! to String is infallible");
            for field in fields {
                writeln!(out, "  {}: {};", field.name, render_ts_type(&field.ty))
                    .expect("write! to String is infallible");
            }
            let disc = u
                .discriminant_name
                .as_deref()
                .expect("named-group union missing discriminant_name");
            writeln!(out, "  {}: {};", disc, render_ts_union(u))
                .expect("write! to String is infallible");
            writeln!(out, "}}").expect("write! to String is infallible");
        }
    }
}

// Flat-union TS shape: a union of single-variant objects, each
// inlining the base fields. Mirror of emit_zod_flat_union on the
// runtime side.
fn render_ts_flat_union(base_fields: &[StructField], u: &Union) -> String {
    let mut parts: Vec<String> = Vec::new();
    for variant in &u.variants {
        let mut props: Vec<String> = base_fields
            .iter()
            .map(|f| format!("{}: {}", f.name, render_ts_type(&f.ty)))
            .collect();
        let inner = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "null".to_owned(),
            other => render_ts_type(other),
        };
        props.push(format!("{}: {}", variant.name, inner));
        parts.push(format!("{{ {} }}", props.join("; ")));
    }
    parts.join(" | ")
}

fn render_ts_union(u: &Union) -> String {
    let mut parts: Vec<String> = Vec::new();
    for variant in &u.variants {
        let inner = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "null".to_owned(),
            other => render_ts_type(other),
        };
        parts.push(format!("{{ {name}: {inner} }}", name = variant.name));
    }
    parts.join(" | ")
}

fn render_field(field: &StructField) -> String {
    render_zod_type(&field.ty)
}

fn render_zod_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_zod_scalar(*s).to_owned(),
        FieldType::StructRef(name) => format!("{name}Schema"),
        FieldType::EnumRef(name) => format!("{name}Schema"),
        // `z.array(T).readonly()` emits a schema whose inferred output
        // type is `readonly T[]` (zod 4 ZodReadonly wrapping ZodArray).
        // Pairs with the `readonly T[]` we emit on the matching TS
        // interface field below — without both, the `z.ZodType<Bundle>`
        // declaration would type-mismatch (zod's inferred type wouldn't
        // include the readonly modifier). Per cloister-818f2b.
        FieldType::List(inner) => format!("z.array({}).readonly()", render_zod_type(inner)),
    }
}

fn render_zod_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::Void => "z.void()",
        ScalarType::Bool => "z.boolean()",
        ScalarType::Int8 | ScalarType::Int16 | ScalarType::Int32 | ScalarType::Int64 => {
            "z.number().int()"
        }
        ScalarType::UInt8 | ScalarType::UInt16 | ScalarType::UInt32 | ScalarType::UInt64 => {
            "z.number().int().nonnegative()"
        }
        ScalarType::Float32 | ScalarType::Float64 => "z.number()",
        ScalarType::Text => "z.string()",
        ScalarType::Data => "z.instanceof(Uint8Array)",
    }
}

fn render_ts_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_ts_scalar(*s).to_owned(),
        FieldType::StructRef(name) => name.clone(),
        FieldType::EnumRef(name) => name.clone(),
        FieldType::List(inner) => {
            // `readonly T[]` — capnp lists are conceptually read-only
            // from the TS consumer's point of view (the wire is the
            // source of truth; mutating an in-memory copy doesn't
            // change anything load-bearing). Emitting readonly here
            // pairs with the matching `z.array(...).readonly()` on
            // the zod side; together they make immutability load-
            // bearing at compile time. Per cloister-818f2b.
            //
            // `readonly T[]` rather than `(readonly T)[]` — TS array
            // postfix binds tighter than readonly, so `readonly T[]`
            // is `ReadonlyArray<T>`, which is what we want. The bare
            // form is unambiguous for scalars + struct refs. When
            // union types land they'll need explicit parens because
            // `A | B[]` parses as `A | (B[])`; handle then, not now.
            format!("readonly {}[]", render_ts_type(inner))
        }
    }
}

// `export const NAME = <literal> as const;` — the `as const` is the
// load-bearing bit. Without it TS widens object/array literals to
// `string` / `number` / mutable arrays, defeating the whole point of
// declaring a constant in the schema. Per cloister-946a59.
fn emit_const(out: &mut String, c: &Const) {
    writeln!(
        out,
        "export const {name} = {value} as const;",
        name = c.name,
        value = render_const_value(&c.value),
    )
    .expect("write! to String is infallible");
}

fn render_const_value(v: &ConstValue) -> String {
    match v {
        ConstValue::Void => "null".to_owned(),
        ConstValue::Bool(b) => b.to_string(),
        ConstValue::Int(n) => n.to_string(),
        ConstValue::UInt(n) => n.to_string(),
        ConstValue::Float(f) => {
            // JSON-friendly float emit: avoid `inf`/`nan`/scientific
            // edge cases by routing through Rust's default Display. The
            // const must lex as a valid TS numeric literal.
            if f.is_finite() {
                let s = format!("{f}");
                // Force a decimal point so `1.0` doesn't widen to `1`
                // (which would let TS infer `number` more eagerly when
                // composing with other ints). Cheap textual check.
                if s.contains('.') || s.contains('e') || s.contains('E') {
                    s
                } else {
                    format!("{s}.0")
                }
            } else {
                // Inf/NaN aren't valid TS const literals — surface as a
                // typed sentinel so the build breaks visibly rather
                // than emitting bare `NaN` (which is a wide `number`).
                format!("Number.{:?}", f).to_lowercase()
            }
        }
        ConstValue::Text(s) => format!("\"{}\"", escape_ts_string(s)),
        ConstValue::Enum(name) => format!("\"{name}\""),
        ConstValue::List(items) => {
            let inner: Vec<String> = items.iter().map(render_const_value).collect();
            format!("[{}]", inner.join(", "))
        }
        ConstValue::Struct(fields) => {
            let inner: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}: {}", render_const_value(v)))
                .collect();
            format!("{{ {} }}", inner.join(", "))
        }
    }
}

// Minimal TS string escape: backslash, double-quote, newline, carriage
// return, tab. Sufficient for the const values we ingest from capnp
// (capnp Text is already UTF-8, no embedded NULs).
fn escape_ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

fn render_ts_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::Void => "void",
        ScalarType::Bool => "boolean",
        ScalarType::Int8
        | ScalarType::Int16
        | ScalarType::Int32
        | ScalarType::Int64
        | ScalarType::UInt8
        | ScalarType::UInt16
        | ScalarType::UInt32
        | ScalarType::UInt64
        | ScalarType::Float32
        | ScalarType::Float64 => "number",
        ScalarType::Text => "string",
        ScalarType::Data => "Uint8Array",
    }
}
