// Code generated by capnpc-go. DO NOT EDIT.

package binding

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type BindingRecord capnp.Struct

// BindingRecord_TypeID is the unique identifier for the type BindingRecord.
const BindingRecord_TypeID = 0xb25434baab461394

func NewBindingRecord(s *capnp.Segment) (BindingRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7})
	return BindingRecord(st), err
}

func NewRootBindingRecord(s *capnp.Segment) (BindingRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7})
	return BindingRecord(st), err
}

func ReadRootBindingRecord(msg *capnp.Message) (BindingRecord, error) {
	root, err := msg.Root()
	return BindingRecord(root.Struct()), err
}

func (s BindingRecord) String() string {
	str, _ := text.Marshal(0xb25434baab461394, capnp.Struct(s))
	return str
}

func (s BindingRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BindingRecord) DecodeFromPtr(p capnp.Ptr) BindingRecord {
	return BindingRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BindingRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BindingRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BindingRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BindingRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BindingRecord) TargetNodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BindingRecord) HasTargetNodeId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BindingRecord) TargetNodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BindingRecord) SetTargetNodeId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BindingRecord) RefToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BindingRecord) HasRefToken() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BindingRecord) RefTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BindingRecord) SetRefToken(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s BindingRecord) ConstructNodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s BindingRecord) HasConstructNodeId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s BindingRecord) ConstructNodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s BindingRecord) SetConstructNodeId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s BindingRecord) RefSiteNodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s BindingRecord) HasRefSiteNodeId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s BindingRecord) RefSiteNodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s BindingRecord) SetRefSiteNodeId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s BindingRecord) RefUri() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s BindingRecord) HasRefUri() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s BindingRecord) RefUriBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s BindingRecord) SetRefUri(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s BindingRecord) RefRange() (common.Range, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return common.Range(p.Struct()), err
}

func (s BindingRecord) HasRefRange() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s BindingRecord) SetRefRange(v common.Range) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewRefRange sets the refRange field to a newly
// allocated common.Range struct, preferring placement in s's segment.
func (s BindingRecord) NewRefRange() (common.Range, error) {
	ss, err := common.NewRange(capnp.Struct(s).Segment())
	if err != nil {
		return common.Range{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s BindingRecord) ParseGen() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s BindingRecord) SetParseGen(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s BindingRecord) Qualifier() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s BindingRecord) HasQualifier() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s BindingRecord) QualifierBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s BindingRecord) SetQualifier(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

// BindingRecord_List is a list of BindingRecord.
type BindingRecord_List = capnp.StructList[BindingRecord]

// NewBindingRecord creates a new list of BindingRecord.
func NewBindingRecord_List(s *capnp.Segment, sz int32) (BindingRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7}, sz)
	return capnp.StructList[BindingRecord](l), err
}

// BindingRecord_Future is a wrapper for a BindingRecord promised by a client call.
type BindingRecord_Future struct{ *capnp.Future }

func (f BindingRecord_Future) Struct() (BindingRecord, error) {
	p, err := f.Future.Ptr()
	return BindingRecord(p.Struct()), err
}
func (p BindingRecord_Future) RefRange() common.Range_Future {
	return common.Range_Future{Future: p.Future.Field(5, nil)}
}

const schema_9c0c8cd3c5b1329a = "x\xdaL\x8f\xbd\x8a\xd4P\x18\x86\xdf\xf7;\xf9qa" +
	"VsHz\xf7\x0a\x04\x7f\xaam\x14\x0be\xb7\x08\x9e" +
	"d\xf7\x02brf\x88J2\x9e\xcd\xde\x80\xb5\xe5T" +
	"\xe2\x1dX)\x880\xd62\xadb\xa3`\xe1_\xa10" +
	"\x8d0\x82\x85C$\x0c.S~\x0f\x0f\xcf\xc7\x1b}" +
	"\xbb\xe1]\xde]\x08\xc4\xec\xf9A?\x8bo=\x9b_" +
	";z\x01s\x9e\xec\x9f\\y\xfe\xe6\xfd\xe3\xd1S\xf8" +
	"a\x08\xc4\x07\xfc\x1a\x1f3\x04\xae\x1a.\x88\xb4\xbf[" +
	"7U\xddL.IYL\x9b\xe9\xfe\xcd\xcd\x99\xd92" +
	"l]u\x874{\xca\x03<\x02\xfa\xdd=\xc0\xbcU" +
	"4\x9f\x84\x9aL8\xc0\x8f\x87\x80\xf9\xa0h\xbe\x0b\xb5" +
	"HB\x01\xf4\x97G\x80\xf9\xach\x96B\xadTB\x05" +
	"\xe8\x9f\x0e0?\x14\xcdJ\xa8=/\xa1\x07\xe8_\xfb" +
	"\x80Y*\x9a?B\xed\xfb\x09}@\xff\x1e\x9a+\xc5" +
	"\x8cB\x06\x09\x03@\xaf\x07\xf6W1?G\xa1\x0e\x83" +
	"d\x18\x11\xfb\xcc\x80\xdc\xa3b\x1eQ\xd8w\x85\x9b\xd8" +
	".mq\xa1\xb2\x07\x15G\x10\x8e\xc0\xde\xd9\xf1Q{" +
	"\xdf6\x00\xceX\xd96'\x9d;-\xd9\xa5\xed c" +
	"\xdb\xce\xeb\xce\xa6\xb8\xd8nW\xae;;>v\xf5\xb6" +
	"\x96\x15\xcd\xc4\x0e\xd1h}8\x7f\xfdr\xb6\xfb\x0ad" +
	"\x04\xf6\xd3\xc2\x9d\xd8\xdb\x9b\x87;\x10\xee\x80\xfd\xc3\xd3" +
	"\xe2A=\xae-\xe8\xfe7\xfe\x05\x00\x00\xff\xff\xfd\xfb" +
	"d\x9a"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_9c0c8cd3c5b1329a,
		Nodes: []uint64{
			0xb25434baab461394,
		},
		Compressed: true,
	})
}
