/* Generated by cbindgen — do not edit manually. */

#ifndef LEYLINE_FS_H
#define LEYLINE_FS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a ley-line graph context.
 * Wraps SqliteGraphAdapter which queries the `nodes` table.
 */
typedef struct LeylineCtx LeylineCtx;

/**
 * Open the arena and return an opaque handle.
 *
 * Returns null on failure. Caller must call `leyline_close` to free.
 *
 * # Safety
 * `path` must be a valid null-terminated C string pointing to the control file.
 */
 struct LeylineCtx *leyline_open(const char *path);

/**
 * Close a handle, freeing the underlying connection.
 *
 * # Safety
 * `ctx` must be a valid pointer from `leyline_open`, or null.
 */
 void leyline_close(struct LeylineCtx *ctx);

/**
 * Get a node by ID. Writes JSON `{"id":"...","name":"...","kind":0|1,"size":N,"mtime":N}`.
 *
 * # Safety
 * `ctx` from `leyline_open`. `id` null-terminated. `out_buf` has `len` writable bytes.
 */

int32_t leyline_get_node(const struct LeylineCtx *ctx,
                         const char *id,
                         uint8_t *out_buf,
                         uintptr_t len);

/**
 * List children of a node. Writes JSON array of node objects.
 *
 * # Safety
 * `ctx` from `leyline_open`. `parent_id` null-terminated. `out_buf` has `len` writable bytes.
 */

int32_t leyline_list_children(const struct LeylineCtx *ctx,
                              const char *parent_id,
                              uint8_t *out_buf,
                              uintptr_t len);

/**
 * Look up a child by name under a parent. Writes JSON node object.
 *
 * # Safety
 * `ctx` from `leyline_open`. `parent_id` and `name` null-terminated.
 */

int32_t leyline_lookup_child(const struct LeylineCtx *ctx,
                             const char *parent_id,
                             const char *name,
                             uint8_t *out_buf,
                             uintptr_t len);

/**
 * Read file content (the `record` column) for a node.
 *
 * # Safety
 * `ctx` from `leyline_open`. `id` null-terminated. `out_buf` has `len` writable bytes.
 */

int32_t leyline_read_content(const struct LeylineCtx *ctx,
                             const char *id,
                             uint8_t *out_buf,
                             uintptr_t len,
                             uint64_t offset);

/**
 * Legacy alias for `leyline_get_node`. Queries the `nodes` table (not the old `results` table).
 */

int32_t leyline_query(const struct LeylineCtx *ctx,
                      const char *id,
                      uint8_t *out_buf,
                      uintptr_t len);

/**
 * KNN search over the attached VectorIndex.
 *
 * Returns a heap-allocated JSON C string: `[{"id":"...","distance":0.023}, ...]`.
 * Returns null if no VectorIndex is attached, ctx is null, or on error.
 * Caller must free the returned string with `leyline_free_string`.
 */
char *leyline_knn_search(const struct LeylineCtx *ctx,
                         const float *query_floats,
                         uintptr_t dim,
                         uintptr_t k);

/**
 * Free a string returned by `leyline_knn_search`.
 *
 * `ptr` must be a pointer returned by `leyline_knn_search`, or null.
 */
void leyline_free_string(char *ptr);

#endif  /* LEYLINE_FS_H */
