// Code generated by capnpc-go. DO NOT EDIT.

package source

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "github.com/agentic-research/ley-line-open/clients/go/leyline-schema/common"
)

type SourceFile capnp.Struct

// SourceFile_TypeID is the unique identifier for the type SourceFile.
const SourceFile_TypeID = 0xed2c74549e5090f1

func NewSourceFile(s *capnp.Segment) (SourceFile, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return SourceFile(st), err
}

func NewRootSourceFile(s *capnp.Segment) (SourceFile, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return SourceFile(st), err
}

func ReadRootSourceFile(msg *capnp.Message) (SourceFile, error) {
	root, err := msg.Root()
	return SourceFile(root.Struct()), err
}

func (s SourceFile) String() string {
	str, _ := text.Marshal(0xed2c74549e5090f1, capnp.Struct(s))
	return str
}

func (s SourceFile) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SourceFile) DecodeFromPtr(p capnp.Ptr) SourceFile {
	return SourceFile(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SourceFile) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SourceFile) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SourceFile) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SourceFile) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SourceFile) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SourceFile) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SourceFile) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SourceFile) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s SourceFile) Language() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SourceFile) HasLanguage() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SourceFile) LanguageBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SourceFile) SetLanguage(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SourceFile) CanonicalPath() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s SourceFile) HasCanonicalPath() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s SourceFile) CanonicalPathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s SourceFile) SetCanonicalPath(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s SourceFile) ContentHash() (common.Hash, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return common.Hash(p.Struct()), err
}

func (s SourceFile) HasContentHash() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s SourceFile) SetContentHash(v common.Hash) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewContentHash sets the contentHash field to a newly
// allocated common.Hash struct, preferring placement in s's segment.
func (s SourceFile) NewContentHash() (common.Hash, error) {
	ss, err := common.NewHash(capnp.Struct(s).Segment())
	if err != nil {
		return common.Hash{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s SourceFile) Mtime() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s SourceFile) SetMtime(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s SourceFile) Size() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s SourceFile) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// SourceFile_List is a list of SourceFile.
type SourceFile_List = capnp.StructList[SourceFile]

// NewSourceFile creates a new list of SourceFile.
func NewSourceFile_List(s *capnp.Segment, sz int32) (SourceFile_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4}, sz)
	return capnp.StructList[SourceFile](l), err
}

// SourceFile_Future is a wrapper for a SourceFile promised by a client call.
type SourceFile_Future struct{ *capnp.Future }

func (f SourceFile_Future) Struct() (SourceFile, error) {
	p, err := f.Future.Ptr()
	return SourceFile(p.Struct()), err
}
func (p SourceFile_Future) ContentHash() common.Hash_Future {
	return common.Hash_Future{Future: p.Future.Field(3, nil)}
}

const schema_9bd2953355bd438c = "x\xdaD\xc8\xbfJ\xeb`\x18\x06\xf0\xe7y\xbf\xe4\x94" +
	"\x1eZN?\x9a\xe1 JqpPD\xd0nNB" +
	"A\xc4\xa9/*\xce1\x866\xd0&\xa5M\x17\xafA" +
	"\xd0\xa1\x0e\xe2\x1f\x1c\x14\x1c\x14:XPP\x10GG" +
	"\xafC\x07\xaf \xa2C\x1d\x7f\xbf\xd2h\xc5Y,&" +
	"\x02\xd1I\xf7O\xf6yX?\xdfL\xe7?\xa0EJ" +
	"\xb6_{\xda\xaa\x1e\xbd\x9d\xc0ur@y\x8a/\xe5" +
	"\x19\xe6\x80\xea4\xb7\x89Z\xd6K\xfa\xdd \\\x08\xc4" +
	"\xef\xc4\x9d\xe5\x8d\x1f\xadF\xad\x10uR\xff\x1b\x07p" +
	"\x08\xd8\xe3\x09@\x07\x86z!\xb4\xa4\xc7\xef<[\x07" +
	"\xf4\xd4P\xaf\x85V\xc4\xa3\x00\xf6\xaa\x0b\xe8\xa5\xa1\x0e" +
	"\x85\xd6\x18\x8f\x06\xb0\xb7;\x80\xde\x18\xea\xbd\x90\x8eG" +
	"\x07\xb0\xa3%@\x87\x86\xfa(\xb4.=\xba\x80}\x98" +
	"\x03\xf4\xceP\x9f\x85&\xdae\x01\xc2\x02\x98\xb5\xfc\xb8" +
	"\xd1\xf7\x1b!\x80\xf1\x05~\x9c\xc4Q\xe0\xa3\xd2\xaa\xfb" +
	"i\xf3\xf7\x938\x0d\xe3t\x0d9\xbf\xd7d){\x9d" +
	"\xfd{\xd0\x1c8\xef\x00Y\x02+\xed4j\x87\xccC" +
	"\x98\x07\xff\xf5\xa2\xbd1\xbe\x02\x00\x00\xff\xff\xacXF" +
	"\xc8"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_9bd2953355bd438c,
		Nodes: []uint64{
			0xed2c74549e5090f1,
		},
		Compressed: true,
	})
}
